project:
  type: website

website:
  title: "ISSS624"
  navbar:
    left: 
      - text: Hands-on Exercises
        menu: 
        - text: Hands-on Exercise 1
          href: Hands-on_Ex1/Hands-on Exercise 1.qmd
        - text: Hands-on Exercise 2
          href: Hands-on Ex2/Hands-on Ex2.qmd
      - text: In-class Exercises
        menu: 
          - text: In-class Exercises 1
            href: In-class_ex1.qmd
      - text: Take home Exercises
        menu: 
          - text: Take home Exerciese 1
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

