project:
  type: website

website:
  title: "ISSS624"
  navbar:
    left: 
      - text: Hands-on Exercises
        menu: 
        - text: Hands-on Exercise 1
          href: Hands-on_Ex1/Hands-on Exercise 1.qmd
        - text: Hands-on Exercise 2
          href: Hands-on Ex2/Hands-on Ex2.qmd
        - text: Hands-on Exercise 3
          href: Hands-on Exercise/3/Hands-on Exercise 3.qmd
      - text: In-class Exercises
        menu: 
          - text: In-class Exercises 1
            href: In-class_Ex/In-class_Ex1/In-class_ex1.qmd
          - text: In-class Exercises 2
            href: In-class_Ex/in-class ex 2.qmd
          - text: In-class Exercises 3
            href: In-class_Ex/In-class Ex3/In-class Exercise 3.qmd
      - text: Take home Exercises
        menu: 
          - text: Take home Exercise 1
            href: Take-home Exercise/Take-home Ex1.qmd
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

