<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.1.189">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>ISSS624 - Take home ex1</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>


<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">ISSS624</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-hands-on-exercises" role="button" data-bs-toggle="dropdown" aria-expanded="false">Hands-on Exercises</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-hands-on-exercises">    
        <li>
    <a class="dropdown-item" href="../Hands-on_Ex1/Hands-on Exercise 1.html">
 <span class="dropdown-text">Hands-on Exercise 1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../Hands-on Ex2/Hands-on Ex2.html">
 <span class="dropdown-text">Hands-on Exercise 2</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-in-class-exercises" role="button" data-bs-toggle="dropdown" aria-expanded="false">In-class Exercises</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-in-class-exercises">    
        <li>
    <a class="dropdown-item" href="../In-class_Ex/In-class_Ex1/In-class_ex1.html">
 <span class="dropdown-text">In-class Exercises 1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../In-class_Ex/in-class ex 2.html">
 <span class="dropdown-text">In-class Exercises 2</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-take-home-exercises" role="button" data-bs-toggle="dropdown" aria-expanded="false">Take home Exercises</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-take-home-exercises">    
        <li>
    <a class="dropdown-item" href="../Take-home Exercise/Take-home Ex1.html">
 <span class="dropdown-text">Take home Exercise 1</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html">Home</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../about.html">About</a>
  </li>  
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#overviewd" id="toc-overviewd" class="nav-link active" data-scroll-target="#overviewd">Overviewd</a></li>
  <li><a href="#import-data" id="toc-import-data" class="nav-link" data-scroll-target="#import-data">1 Import data</a>
  <ul class="collapse">
  <li><a href="#import-waterpoint" id="toc-import-waterpoint" class="nav-link" data-scroll-target="#import-waterpoint">1.1 import waterpoint</a></li>
  <li><a href="#import-nigeria-lga-boundary-data" id="toc-import-nigeria-lga-boundary-data" class="nav-link" data-scroll-target="#import-nigeria-lga-boundary-data">1.2 import Nigeria LGA boundary data</a></li>
  </ul></li>
  <li><a href="#data-wrangling" id="toc-data-wrangling" class="nav-link" data-scroll-target="#data-wrangling">2 Data Wrangling</a>
  <ul class="collapse">
  <li><a href="#recoding-na-values-into-string" id="toc-recoding-na-values-into-string" class="nav-link" data-scroll-target="#recoding-na-values-into-string">2.1 Recoding NA values into string</a></li>
  <li><a href="#eda" id="toc-eda" class="nav-link" data-scroll-target="#eda">2.2 EDA</a></li>
  </ul></li>
  <li><a href="#extracting-water-point-data" id="toc-extracting-water-point-data" class="nav-link" data-scroll-target="#extracting-water-point-data">3 Extracting Water Point Data</a>
  <ul class="collapse">
  <li><a href="#extracting-the-functional-water-point-data" id="toc-extracting-the-functional-water-point-data" class="nav-link" data-scroll-target="#extracting-the-functional-water-point-data">3.1 Extracting the functional water point data</a></li>
  <li><a href="#extracting-non-funtional-water-point" id="toc-extracting-non-funtional-water-point" class="nav-link" data-scroll-target="#extracting-non-funtional-water-point">3.2 Extracting non-funtional water point</a></li>
  <li><a href="#extracting-water-point-with-unknown-class" id="toc-extracting-water-point-with-unknown-class" class="nav-link" data-scroll-target="#extracting-water-point-with-unknown-class">3.3 Extracting water point with Unknown class</a></li>
  </ul></li>
  <li><a href="#performing-point-in-polygon-count" id="toc-performing-point-in-polygon-count" class="nav-link" data-scroll-target="#performing-point-in-polygon-count">4 Performing Point-in-Polygon Count</a></li>
  <li><a href="#saving-the-analytical-data-table" id="toc-saving-the-analytical-data-table" class="nav-link" data-scroll-target="#saving-the-analytical-data-table">5 Saving the Analytical Data Table</a></li>
  <li><a href="#visualising-the-spatial-dsitribution-of-water-points" id="toc-visualising-the-spatial-dsitribution-of-water-points" class="nav-link" data-scroll-target="#visualising-the-spatial-dsitribution-of-water-points">6 Visualising the spatial dsitribution of water points</a></li>
  <li><a href="#outliersclusters-analysis" id="toc-outliersclusters-analysis" class="nav-link" data-scroll-target="#outliersclusters-analysis">2 Outliers/clusters analysis</a>
  <ul class="collapse">
  <li><a href="#global-spatial-autocorrelation" id="toc-global-spatial-autocorrelation" class="nav-link" data-scroll-target="#global-spatial-autocorrelation">2.1 Global Spatial Autocorrelation</a>
  <ul class="collapse">
  <li><a href="#computing-contiguity-spatial-weights" id="toc-computing-contiguity-spatial-weights" class="nav-link" data-scroll-target="#computing-contiguity-spatial-weights">2.1.1 Computing Contiguity Spatial Weights</a></li>
  <li><a href="#row-standardised-weights-matrix" id="toc-row-standardised-weights-matrix" class="nav-link" data-scroll-target="#row-standardised-weights-matrix">2.1.2 Row-standardised weights matrix</a></li>
  <li><a href="#global-spatial-autocorrelation-morans-i" id="toc-global-spatial-autocorrelation-morans-i" class="nav-link" data-scroll-target="#global-spatial-autocorrelation-morans-i">2.1.3 Global Spatial Autocorrelation: Moran’s I</a></li>
  </ul></li>
  <li><a href="#spatial-correlogram" id="toc-spatial-correlogram" class="nav-link" data-scroll-target="#spatial-correlogram">2.2 Spatial Correlogram</a>
  <ul class="collapse">
  <li><a href="#compute-morans-i-correlogram" id="toc-compute-morans-i-correlogram" class="nav-link" data-scroll-target="#compute-morans-i-correlogram">2.2.1 Compute Moran’s I correlogram</a></li>
  </ul></li>
  <li><a href="#cluster-and-outlier-analysis" id="toc-cluster-and-outlier-analysis" class="nav-link" data-scroll-target="#cluster-and-outlier-analysis">2.3 Cluster and Outlier Analysis</a>
  <ul class="collapse">
  <li><a href="#functional-waterpoint" id="toc-functional-waterpoint" class="nav-link" data-scroll-target="#functional-waterpoint">2.3.1 Functional waterpoint</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#hotspot-area-analysis" id="toc-hotspot-area-analysis" class="nav-link" data-scroll-target="#hotspot-area-analysis">3 Hotspot area analysis</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Take home ex1</h1>
</div>



<div class="quarto-title-meta">

    
    
  </div>
  

</header>

<section id="overviewd" class="level2">
<h2 class="anchored" data-anchor-id="overviewd">Overviewd</h2>
</section>
<section id="import-data" class="level2">
<h2 class="anchored" data-anchor-id="import-data">1 Import data</h2>
<p>First of all we load the package that needed: sf, spdep, tmap, tidyverse,dplyr, funModeling</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(sf, spdep, tmap, tidyverse,dplyr, funModeling)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>There are two dataset we used:</p>
<ul>
<li><p>geo_export:</p></li>
<li><p>nga_admbnda_adm2_osgof_20190417</p></li>
</ul>
<p>change it to shorter name</p>
<section id="import-waterpoint" class="level3">
<h3 class="anchored" data-anchor-id="import-waterpoint">1.1 import waterpoint</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>wp<span class="ot">&lt;-</span> <span class="fu">st_read</span>(<span class="at">dsn=</span><span class="st">"geodata"</span>,</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>             <span class="at">layer=</span><span class="st">"geo_export"</span>,</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">crs=</span><span class="dv">4326</span>) <span class="sc">%&gt;%</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(clean_coun<span class="sc">==</span><span class="st">"Nigeria"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>in the</p>
<p>Then I saved it into wp_nga.rds. In this way I can delete geo_export data which is too large to git push.</p>
<p>I add #eval: false to make sure the code chunk will only display</p>
<p><a href="https://quarto.org/docs/computations/execution-options.html">ref</a></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>wp_nga<span class="ot">&lt;-</span><span class="fu">write_rds</span>(wp,<span class="st">"geodata/wp_nga.rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="import-nigeria-lga-boundary-data" class="level3">
<h3 class="anchored" data-anchor-id="import-nigeria-lga-boundary-data">1.2 import Nigeria LGA boundary data</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>nga<span class="ot">&lt;-</span> <span class="fu">st_read</span>(<span class="at">dsn=</span><span class="st">"geodata"</span>,</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>             <span class="at">layer=</span><span class="st">"geoBoundaries-NGA-ADM2"</span>,</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">crs=</span><span class="dv">4326</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Reading layer `geoBoundaries-NGA-ADM2' from data source 
  `D:\Xu-Siyi\ISSS624\Take-home Exercise\geodata' using driver `ESRI Shapefile'
Simple feature collection with 774 features and 5 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: 2.668534 ymin: 4.273007 xmax: 14.67882 ymax: 13.89442
Geodetic CRS:  WGS 84</code></pre>
</div>
</div>
</section>
</section>
<section id="data-wrangling" class="level2">
<h2 class="anchored" data-anchor-id="data-wrangling">2 Data Wrangling</h2>
<section id="recoding-na-values-into-string" class="level3">
<h3 class="anchored" data-anchor-id="recoding-na-values-into-string">2.1 Recoding NA values into string</h3>
<p>In the code chunk below, replace_na() is used to recode all the NA values in status_cle field into Unknown.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>wp_nga <span class="ot">&lt;-</span> <span class="fu">read_rds</span>(<span class="st">"geodata/wp_nga.rds"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">status_cle =</span> <span class="fu">replace_na</span>(status_cle, <span class="st">"Unknown"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="eda" class="level3">
<h3 class="anchored" data-anchor-id="eda">2.2 EDA</h3>
<p>In the code chunk below, freq() of funModeling package is used to display the distribution of status_cle field in wp_nga.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">freq</span>(<span class="at">data=</span>wp_nga, </span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">input =</span> <span class="st">'status_cle'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: The `&lt;scale&gt;` argument of `guides()` cannot be `FALSE`. Use "none" instead as
of ggplot2 3.3.4.
ℹ The deprecated feature was likely used in the funModeling package.
  Please report the issue at &lt;https://github.com/pablo14/funModeling/issues&gt;.</code></pre>
</div>
<div class="cell-output-display">
<p><img src="Take-home-Ex1_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>                        status_cle frequency percentage cumulative_perc
1                       Functional     16919      83.29           83.29
2      Functional but needs repair      2102      10.35           93.64
3        Functional but not in use       579       2.85           96.49
4                          Unknown       396       1.95           98.44
5         Abandoned/Decommissioned       234       1.15           99.59
6                        Abandoned        76       0.37           99.96
7                   Non-Functional         5       0.02           99.98
8 Non functional due to dry season         2       0.01          100.00</code></pre>
</div>
</div>
</section>
</section>
<section id="extracting-water-point-data" class="level2">
<h2 class="anchored" data-anchor-id="extracting-water-point-data">3 Extracting Water Point Data</h2>
<p>In this section, we will extract the water point records by using classes in status_cle field.</p>
<section id="extracting-the-functional-water-point-data" class="level3">
<h3 class="anchored" data-anchor-id="extracting-the-functional-water-point-data">3.1 Extracting the functional water point data</h3>
<p>in this code chunk below, filter() is used to select functional water points</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>wpt_functional <span class="ot">&lt;-</span> wp_nga <span class="sc">%&gt;%</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(status_cle <span class="sc">%in%</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>           <span class="fu">c</span>(<span class="st">"Functional"</span>, </span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>             <span class="st">"Functional but not in use"</span>,</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>             <span class="st">"Functional but needs repair"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">freq</span>(<span class="at">data=</span>wpt_functional, </span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">input =</span> <span class="st">'status_cle'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Take-home-Ex1_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>                   status_cle frequency percentage cumulative_perc
1                  Functional     16919      86.32           86.32
2 Functional but needs repair      2102      10.72           97.04
3   Functional but not in use       579       2.95          100.00</code></pre>
</div>
</div>
</section>
<section id="extracting-non-funtional-water-point" class="level3">
<h3 class="anchored" data-anchor-id="extracting-non-funtional-water-point">3.2 Extracting non-funtional water point</h3>
<p>In the code chunk below, filter() of dplyr is used to select non-functional water points.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>wpt_nonfunctional <span class="ot">&lt;-</span> wp_nga <span class="sc">%&gt;%</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(status_cle <span class="sc">%in%</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>           <span class="fu">c</span>(<span class="st">"Abandoned/Decommissioned"</span>, </span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>             <span class="st">"Abandoned"</span>,</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>             <span class="st">"Non-Functional"</span>,</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>             <span class="st">"Non functional due to dry season"</span>,</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>             <span class="st">"Non-Functional due to dry season"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">freq</span>(<span class="at">data=</span>wpt_nonfunctional, </span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">input =</span> <span class="st">'status_cle'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Take-home-Ex1_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>                        status_cle frequency percentage cumulative_perc
1         Abandoned/Decommissioned       234      73.82           73.82
2                        Abandoned        76      23.97           97.79
3                   Non-Functional         5       1.58           99.37
4 Non functional due to dry season         2       0.63          100.00</code></pre>
</div>
</div>
</section>
<section id="extracting-water-point-with-unknown-class" class="level3">
<h3 class="anchored" data-anchor-id="extracting-water-point-with-unknown-class">3.3 Extracting water point with Unknown class</h3>
<p>In the code chunk below, <code>filter()</code> of dplyr is used to select water points with unknown status.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>wpt_unknown <span class="ot">&lt;-</span> wp_nga <span class="sc">%&gt;%</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(status_cle <span class="sc">==</span> <span class="st">"Unknown"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">freq</span>(<span class="at">data=</span>wpt_unknown, </span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">input =</span> <span class="st">'status_cle'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Take-home-Ex1_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>  status_cle frequency percentage cumulative_perc
1    Unknown       396        100             100</code></pre>
</div>
</div>
</section>
</section>
<section id="performing-point-in-polygon-count" class="level2">
<h2 class="anchored" data-anchor-id="performing-point-in-polygon-count">4 Performing Point-in-Polygon Count</h2>
<p>The point-in-polygon (PIP) problem asks whether a given point in the plane lies inside, outside, or on the boundary of a polygon.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>nga_wp <span class="ot">&lt;-</span> nga <span class="sc">%&gt;%</span> </span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="st">`</span><span class="at">total wpt</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">lengths</span>(</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">st_intersects</span>(nga, wp_nga))) <span class="sc">%&gt;%</span></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="st">`</span><span class="at">wpt functional</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">lengths</span>(</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">st_intersects</span>(nga, wpt_functional))) <span class="sc">%&gt;%</span></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="st">`</span><span class="at">wpt non-functional</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">lengths</span>(</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">st_intersects</span>(nga, wpt_nonfunctional))) <span class="sc">%&gt;%</span></span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="st">`</span><span class="at">wpt unknown</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">lengths</span>(</span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">st_intersects</span>(nga, wpt_unknown)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="saving-the-analytical-data-table" class="level2">
<h2 class="anchored" data-anchor-id="saving-the-analytical-data-table">5 Saving the Analytical Data Table</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>nga_wp <span class="ot">&lt;-</span> nga_wp <span class="sc">%&gt;%</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">pct_functional =</span> <span class="st">`</span><span class="at">wpt functional</span><span class="st">`</span><span class="sc">/</span><span class="st">`</span><span class="at">total wpt</span><span class="st">`</span>) <span class="sc">%&gt;%</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="st">`</span><span class="at">pct_non-functional</span><span class="st">`</span> <span class="ot">=</span> <span class="st">`</span><span class="at">wpt non-functional</span><span class="st">`</span><span class="sc">/</span><span class="st">`</span><span class="at">total wpt</span><span class="st">`</span>) <span class="sc">%&gt;%</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="dv">3</span><span class="sc">:</span><span class="dv">4</span>, <span class="dv">9</span><span class="sc">:</span><span class="dv">10</span>, <span class="dv">18</span><span class="sc">:</span><span class="dv">23</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Things to learn from the code chunk above:</p>
<p><code>mutate()</code> of <strong>dplyr</strong> package is used to derive two fields namely pct_functional and pct_non-functional.</p>
<p>to keep the file size small, <code>select()</code> of <strong>dplyr</strong> is used to retain only field 3,4,9,10, 18,19,20,21,22,and 23.</p>
<p>Now, you have the tidy sf data table subsequent analysis. We will save the sf data table into rds format.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">write_rds</span>(nga_wp, <span class="st">"geodata/nga_wp.rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>There is only data file we use, nga_wp.rds, which is the combination of the geospatial and aspatial data.</p>
</section>
<section id="visualising-the-spatial-dsitribution-of-water-points" class="level2">
<h2 class="anchored" data-anchor-id="visualising-the-spatial-dsitribution-of-water-points">6 Visualising the spatial dsitribution of water points</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>nga_wp <span class="ot">&lt;-</span> <span class="fu">read_rds</span>(<span class="st">"geodata/nga_wp.rds"</span>)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>total <span class="ot">&lt;-</span> <span class="fu">qtm</span>(nga_wp, <span class="st">"total wpt"</span>)</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>wp_functional <span class="ot">&lt;-</span> <span class="fu">qtm</span>(nga_wp, <span class="st">"wpt functional"</span>)</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>wp_nonfunctional <span class="ot">&lt;-</span> <span class="fu">qtm</span>(nga_wp, <span class="st">"wpt non-functional"</span>)</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>unknown <span class="ot">&lt;-</span> <span class="fu">qtm</span>(nga_wp, <span class="st">"wpt unknown"</span>)</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_arrange</span>(total, wp_functional, wp_nonfunctional, unknown, <span class="at">asp=</span><span class="dv">1</span>, <span class="at">ncol=</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Take-home-Ex1_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid" width="1344"></p>
</div>
</div>
</section>
<section id="outliersclusters-analysis" class="level1">
<h1>2 Outliers/clusters analysis</h1>
<section id="global-spatial-autocorrelation" class="level2">
<h2 class="anchored" data-anchor-id="global-spatial-autocorrelation">2.1 Global Spatial Autocorrelation</h2>
<section id="computing-contiguity-spatial-weights" class="level3">
<h3 class="anchored" data-anchor-id="computing-contiguity-spatial-weights">2.1.1 Computing Contiguity Spatial Weights</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>wm_q <span class="ot">&lt;-</span> <span class="fu">poly2nb</span>(nga_wp, </span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>                <span class="at">queen=</span><span class="cn">TRUE</span>)</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(wm_q)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Neighbour list object:
Number of regions: 774 
Number of nonzero links: 4440 
Percentage nonzero weights: 0.7411414 
Average number of links: 5.736434 
1 region with no links:
86
Link number distribution:

  0   1   2   3   4   5   6   7   8   9  10  11  12  14 
  1   2  14  57 125 182 140 122  72  41  12   4   1   1 
2 least connected regions:
138 560 with 1 link
1 most connected region:
508 with 14 links</code></pre>
</div>
</div>
<p>The summary report above shows that there are 774 area units in Hunan. The most connected area unit has 14 neighbours. There are two area units (138 and 560) with only one neighbours.</p>
</section>
<section id="row-standardised-weights-matrix" class="level3">
<h3 class="anchored" data-anchor-id="row-standardised-weights-matrix">2.1.2 Row-standardised weights matrix</h3>
<p>Now we calculate</p>
<p>Because there is 1 region with no links in the NGA data, I use <code>set.ZeroPolicyOption(TRUE)</code> to create the Weights Matrix.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.ZeroPolicyOption</span>(<span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] FALSE</code></pre>
</div>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>rswm_q <span class="ot">&lt;-</span> <span class="fu">nb2listw</span>(wm_q, </span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>                   <span class="at">style=</span><span class="st">"W"</span>, </span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>                   <span class="at">zero.policy =</span> <span class="cn">TRUE</span></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>                   )</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>rswm_q</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Characteristics of weights list object:
Neighbour list object:
Number of regions: 774 
Number of nonzero links: 4440 
Percentage nonzero weights: 0.7411414 
Average number of links: 5.736434 
1 region with no links:
86

Weights style: W 
Weights constants summary:
    n     nn  S0       S1       S2
W 773 597529 773 285.0658 3198.414</code></pre>
</div>
</div>
</section>
<section id="global-spatial-autocorrelation-morans-i" class="level3">
<h3 class="anchored" data-anchor-id="global-spatial-autocorrelation-morans-i">2.1.3 Global Spatial Autocorrelation: Moran’s I</h3>
<p>Moran’s I is a measure of spatial autocorrelation</p>
<p>I use <code>moran.test()</code> of <strong>spdep</strong> to do Moran’s I statistics testing</p>
<section id="marons-i-test" class="level4">
<h4 class="anchored" data-anchor-id="marons-i-test">2.1.3.1 Maron’s I test</h4>
<section id="funtional-waterpoint" class="level5">
<h5 class="anchored" data-anchor-id="funtional-waterpoint"><strong>(1)</strong> <strong>Funtional waterpoint</strong></h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">moran.test</span>(nga_wp<span class="sc">$</span><span class="st">`</span><span class="at">wpt functional</span><span class="st">`</span>, </span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>           <span class="at">listw=</span>rswm_q, </span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>           <span class="at">zero.policy =</span> <span class="cn">TRUE</span>, </span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>           <span class="at">na.action=</span>na.omit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Moran I test under randomisation

data:  nga_wp$`wpt functional`  
weights: rswm_q  n reduced by no-neighbour observations
  

Moran I statistic standard deviate = 27.729, p-value &lt; 2.2e-16
alternative hypothesis: greater
sample estimates:
Moran I statistic       Expectation          Variance 
      0.597453820      -0.001295337       0.000466245 </code></pre>
</div>
</div>
<p>p-value&lt;0.01, means we reject Null hypothesis.</p>
<section id="如何解释结果" class="level6">
<h6 class="anchored" data-anchor-id="如何解释结果">*如何解释结果</h6>
<p>The code chunk below performs permutation test for Moran's I statistic by using moran.mc() of spdep. A total of 1000 simulation will be performed.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>bperm<span class="ot">=</span> <span class="fu">moran.mc</span>(nga_wp<span class="sc">$</span><span class="st">`</span><span class="at">wpt functional</span><span class="st">`</span>, </span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>                <span class="at">listw=</span>rswm_q, </span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>                <span class="at">nsim=</span><span class="dv">999</span>, </span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>                <span class="at">zero.policy =</span> <span class="cn">TRUE</span>, </span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>                <span class="at">na.action=</span>na.omit)</span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a>bperm</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Monte-Carlo simulation of Moran I

data:  nga_wp$`wpt functional` 
weights: rswm_q  
number of simulations + 1: 1000 

statistic = 0.59745, observed rank = 1000, p-value = 0.001
alternative hypothesis: greater</code></pre>
</div>
</div>
<p>In the code chunk below we use hist() and abline() to visualize Monte Carlo Moran’s I</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(bperm<span class="sc">$</span>res[<span class="dv">1</span><span class="sc">:</span><span class="dv">999</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -0.001937958</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">var</span>(bperm<span class="sc">$</span>res[<span class="dv">1</span><span class="sc">:</span><span class="dv">999</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.0004471542</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(bperm<span class="sc">$</span>res[<span class="dv">1</span><span class="sc">:</span><span class="dv">999</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     Min.   1st Qu.    Median      Mean   3rd Qu.      Max. 
-0.066100 -0.016121 -0.002669 -0.001938  0.011703  0.077458 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(bperm<span class="sc">$</span>res, </span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">freq=</span><span class="cn">TRUE</span>, </span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">breaks=</span><span class="dv">20</span>, </span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab=</span><span class="st">"Simulated Moran's I"</span>)</span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v=</span><span class="dv">0</span>, </span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">col=</span><span class="st">"red"</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Take-home-Ex1_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="什么意思" class="level6">
<h6 class="anchored" data-anchor-id="什么意思">*什么意思</h6>
</section>
</section>
<section id="water-non-fuctional" class="level5">
<h5 class="anchored" data-anchor-id="water-non-fuctional">(2) Water-non fuctional</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">moran.test</span>(nga_wp<span class="sc">$</span><span class="st">`</span><span class="at">wpt non-functional</span><span class="st">`</span>, </span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>           <span class="at">listw=</span>rswm_q, </span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>           <span class="at">zero.policy =</span> <span class="cn">TRUE</span>, </span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>           <span class="at">na.action=</span>na.omit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Moran I test under randomisation

data:  nga_wp$`wpt non-functional`  
weights: rswm_q  n reduced by no-neighbour observations
  

Moran I statistic standard deviate = 10.244, p-value &lt; 2.2e-16
alternative hypothesis: greater
sample estimates:
Moran I statistic       Expectation          Variance 
     0.2144866157     -0.0012953368      0.0004437415 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>bperm<span class="ot">=</span> <span class="fu">moran.mc</span>(nga_wp<span class="sc">$</span><span class="st">`</span><span class="at">wpt non-functional</span><span class="st">`</span>, </span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>                <span class="at">listw=</span>rswm_q, </span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>                <span class="at">nsim=</span><span class="dv">999</span>, </span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>                <span class="at">zero.policy =</span> <span class="cn">TRUE</span>, </span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a>                <span class="at">na.action=</span>na.omit)</span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a>bperm</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Monte-Carlo simulation of Moran I

data:  nga_wp$`wpt non-functional` 
weights: rswm_q  
number of simulations + 1: 1000 

statistic = 0.21449, observed rank = 1000, p-value = 0.001
alternative hypothesis: greater</code></pre>
</div>
</div>
<p>In the code chunk below we use hist() and abline() to visualize Monte Carlo Moran’s I</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(bperm<span class="sc">$</span>res[<span class="dv">1</span><span class="sc">:</span><span class="dv">999</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -0.002834731</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">var</span>(bperm<span class="sc">$</span>res[<span class="dv">1</span><span class="sc">:</span><span class="dv">999</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.0003851432</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(bperm<span class="sc">$</span>res[<span class="dv">1</span><span class="sc">:</span><span class="dv">999</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     Min.   1st Qu.    Median      Mean   3rd Qu.      Max. 
-0.046615 -0.016790 -0.005141 -0.002835  0.009189  0.093353 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(bperm<span class="sc">$</span>res, </span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">freq=</span><span class="cn">TRUE</span>, </span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">breaks=</span><span class="dv">20</span>, </span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab=</span><span class="st">"Simulated Moran's I"</span>)</span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v=</span><span class="dv">0</span>, </span>
<span id="cb50-6"><a href="#cb50-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">col=</span><span class="st">"red"</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Take-home-Ex1_files/figure-html/unnamed-chunk-30-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<section id="什么意思-1" class="level6">
<h6 class="anchored" data-anchor-id="什么意思-1">*什么意思</h6>
</section>
</section>
</section>
</section>
</section>
<section id="spatial-correlogram" class="level2">
<h2 class="anchored" data-anchor-id="spatial-correlogram">2.2 Spatial Correlogram</h2>
<section id="compute-morans-i-correlogram" class="level3">
<h3 class="anchored" data-anchor-id="compute-morans-i-correlogram">2.2.1 Compute Moran’s I correlogram</h3>
<section id="water-functional" class="level4">
<h4 class="anchored" data-anchor-id="water-functional">(1) Water functional</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>MI_corr <span class="ot">&lt;-</span> <span class="fu">sp.correlogram</span>(wm_q, </span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>                          nga_wp<span class="sc">$</span><span class="st">`</span><span class="at">wpt functional</span><span class="st">`</span>, </span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a>                          <span class="at">order=</span><span class="dv">6</span>, </span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a>                          <span class="at">method=</span><span class="st">"I"</span>, </span>
<span id="cb51-5"><a href="#cb51-5" aria-hidden="true" tabindex="-1"></a>                          <span class="at">style=</span><span class="st">"W"</span>)</span>
<span id="cb51-6"><a href="#cb51-6" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(MI_corr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Take-home-Ex1_files/figure-html/unnamed-chunk-31-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(MI_corr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Spatial correlogram for nga_wp$`wpt functional` 
method: Moran's I
           estimate expectation    variance standard deviate Pr(I) two sided
1 (773)  5.9745e-01 -1.2953e-03  4.6625e-04           27.729       &lt; 2.2e-16
2 (773)  4.9033e-01 -1.2953e-03  1.9980e-04           34.781       &lt; 2.2e-16
3 (773)  3.9305e-01 -1.2953e-03  1.2053e-04           35.920       &lt; 2.2e-16
4 (773)  3.2632e-01 -1.2953e-03  8.6612e-05           35.202       &lt; 2.2e-16
5 (773)  2.3144e-01 -1.2953e-03  6.8012e-05           28.221       &lt; 2.2e-16
6 (773)  1.4209e-01 -1.2953e-03  5.6741e-05           19.035       &lt; 2.2e-16
           
1 (773) ***
2 (773) ***
3 (773) ***
4 (773) ***
5 (773) ***
6 (773) ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
</section>
<section id="water-non-functional" class="level4">
<h4 class="anchored" data-anchor-id="water-non-functional">(2) Water non-functional</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>MI_corr <span class="ot">&lt;-</span> <span class="fu">sp.correlogram</span>(wm_q, </span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>                          nga_wp<span class="sc">$</span><span class="st">`</span><span class="at">wpt non-functional</span><span class="st">`</span>, </span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a>                          <span class="at">order=</span><span class="dv">6</span>, </span>
<span id="cb54-4"><a href="#cb54-4" aria-hidden="true" tabindex="-1"></a>                          <span class="at">method=</span><span class="st">"I"</span>, </span>
<span id="cb54-5"><a href="#cb54-5" aria-hidden="true" tabindex="-1"></a>                          <span class="at">style=</span><span class="st">"W"</span>)</span>
<span id="cb54-6"><a href="#cb54-6" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(MI_corr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Take-home-Ex1_files/figure-html/unnamed-chunk-33-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(MI_corr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Spatial correlogram for nga_wp$`wpt non-functional` 
method: Moran's I
           estimate expectation    variance standard deviate Pr(I) two sided
1 (773)  2.1449e-01 -1.2953e-03  4.4374e-04          10.2435       &lt; 2.2e-16
2 (773)  1.0322e-01 -1.2953e-03  1.9016e-04           7.5792       3.478e-14
3 (773)  7.7266e-02 -1.2953e-03  1.1471e-04           7.3351       2.216e-13
4 (773)  5.8938e-02 -1.2953e-03  8.2437e-05           6.6341       3.266e-11
5 (773)  4.0501e-02 -1.2953e-03  6.4736e-05           5.1948       2.049e-07
6 (773)  2.4576e-02 -1.2953e-03  5.4011e-05           3.5203        0.000431
           
1 (773) ***
2 (773) ***
3 (773) ***
4 (773) ***
5 (773) ***
6 (773) ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
</section>
</section>
</section>
<section id="cluster-and-outlier-analysis" class="level2">
<h2 class="anchored" data-anchor-id="cluster-and-outlier-analysis">2.3 Cluster and Outlier Analysis</h2>
<p>I use Local Indicators for Spatial Association (LISA) to detect cluster and/or outlier from functional waterpoint and Not Functional water points of Nigeria</p>
<section id="functional-waterpoint" class="level3">
<h3 class="anchored" data-anchor-id="functional-waterpoint">2.3.1 Functional waterpoint</h3>
<section id="computing-local-morans-i" class="level4">
<h4 class="anchored" data-anchor-id="computing-local-morans-i">2.3.1.1 Computing local Moran’s I</h4>
<p>I use shapeID column because there are duplication “Bassa, Ifelodun, Irepodun, Nasarawa, Obi, Surulere” in shapename column</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a>fips <span class="ot">&lt;-</span> <span class="fu">order</span>(nga_wp<span class="sc">$</span>shapeID)</span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>localMI <span class="ot">&lt;-</span> <span class="fu">localmoran</span>(nga_wp<span class="sc">$</span><span class="st">`</span><span class="at">wpt functional</span><span class="st">`</span>, rswm_q)</span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(localMI)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            Ii          E.Ii       Var.Ii       Z.Ii Pr(z != E(Ii))
1  0.072133151 -3.070532e-04 0.0591657387  0.2978136   7.658454e-01
2 -0.042519745 -1.241765e-05 0.0031954141 -0.7519695   4.520694e-01
3  0.453434964 -5.865912e-04 0.1508598995  1.1689329   2.424307e-01
4 -0.162429843 -9.740804e-05 0.0106857965 -1.5703695   1.163292e-01
5  0.006090939 -4.911403e-06 0.0007563421  0.2216538   8.245834e-01
6  2.719950590 -2.940625e-03 0.3216733273  4.8009012   1.579532e-06</code></pre>
</div>
</div>
<p>localmoran() function returns a matrix of values whose columns are:</p>
<p>Ii: the local Moran’s I statistics</p>
<p>E.Ii: the expectation of local moran statistic under the randomisation hypothesis</p>
<p>Var.Ii: the variance of local moran statistic under the randomisation hypothesis</p>
<p>Z.Ii:the standard deviate of local moran statistic</p>
<p>Pr(): the p-value of local moran statistic</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">printCoefmat</span>(<span class="fu">data.frame</span>(</span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>  localMI[fips,], </span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">row.names=</span>nga_wp<span class="sc">$</span>shapeID[fips]),</span>
<span id="cb59-4"><a href="#cb59-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">check.names=</span><span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                    Ii        E.Ii      Var.Ii        Z.Ii
NGA-ADM2-72505758B10049836  4.5343e-01 -5.8659e-04  2.2658e-01  9.5381e-01
NGA-ADM2-72505758B10063467 -9.6710e-02 -4.8993e-05  9.4429e-03 -9.9471e-01
NGA-ADM2-72505758B10065661 -2.8800e-01 -5.6662e-03  6.1813e-01 -3.5910e-01
NGA-ADM2-72505758B10302610  2.9115e-01 -4.9757e-04  6.3739e-02  1.1552e+00
NGA-ADM2-72505758B10682130  4.5343e-01 -5.8659e-04  9.0281e-02  1.5110e+00
NGA-ADM2-72505758B11317593 -9.3856e-03 -6.0372e-04  9.2915e-02 -2.8810e-02
NGA-ADM2-72505758B1132196   1.3739e-01 -3.0705e-04  3.3677e-02  7.5033e-01
NGA-ADM2-72505758B11373444  4.4896e-01 -5.8659e-04  1.1300e-01  1.3373e+00
NGA-ADM2-72505758B11735424  4.5343e-01 -5.8659e-04  6.4318e-02  1.7902e+00
NGA-ADM2-72505758B11870040  4.5343e-01 -5.8659e-04  9.0281e-02  1.5110e+00
NGA-ADM2-72505758B11997780  4.5343e-01 -5.8659e-04  5.6205e-02  1.9151e+00
NGA-ADM2-72505758B122892   -7.1407e-02 -1.0067e-05  1.9404e-03 -1.6208e+00
NGA-ADM2-72505758B12413588  4.5343e-01 -5.8659e-04  7.5136e-02  1.6564e+00
NGA-ADM2-72505758B1244901   1.8731e-01 -5.4117e-04  5.9340e-02  7.7114e-01
NGA-ADM2-72505758B12596325  4.5343e-01 -5.8659e-04  6.4318e-02  1.7902e+00
NGA-ADM2-72505758B12674914  9.2220e-01 -9.7765e-04  1.5041e-01  2.3804e+00
NGA-ADM2-72505758B12680831  4.5343e-01 -5.8659e-04  9.0281e-02  1.5110e+00
NGA-ADM2-72505758B12769973  4.5343e-01 -5.8659e-04  7.5136e-02  1.6564e+00
NGA-ADM2-72505758B12816297 -1.8706e-02 -1.5863e-06  2.4429e-04 -1.1967e+00
NGA-ADM2-72505758B13021078  4.5343e-01 -5.8659e-04  6.4318e-02  1.7902e+00
NGA-ADM2-72505758B13075745  4.5343e-01 -5.8659e-04  4.4847e-02  2.1439e+00
NGA-ADM2-72505758B13233811  2.2813e-02 -6.5905e-06  1.6959e-03  5.5413e-01
NGA-ADM2-72505758B13380599  6.1078e-02 -1.6230e-04  2.0797e-02  4.2466e-01
NGA-ADM2-72505758B13427126  5.1892e-01 -1.4413e-03  2.2163e-01  1.1053e+00
NGA-ADM2-72505758B13487741  4.5343e-01 -5.8659e-04  7.5136e-02  1.6564e+00
NGA-ADM2-72505758B13685756  2.0082e-01 -1.6230e-04  3.1277e-02  1.1365e+00
NGA-ADM2-72505758B139854    4.5343e-01 -5.8659e-04  1.1300e-01  1.3506e+00
NGA-ADM2-72505758B14016122  4.5343e-01 -5.8659e-04  6.4318e-02  1.7902e+00
NGA-ADM2-72505758B14174427  2.2439e-01 -3.0705e-04  5.9166e-02  9.2378e-01
NGA-ADM2-72505758B14213332  2.1590e-01 -4.1587e-04  8.0125e-02  7.6421e-01
NGA-ADM2-72505758B14369579 -2.3397e-02 -1.6230e-04  2.4989e-02 -1.4698e-01
NGA-ADM2-72505758B14654508 -9.9657e-02 -3.7777e-04  7.2787e-02 -3.6799e-01
NGA-ADM2-72505758B14842261 -1.5058e-01 -1.1721e-04  1.1236e-02 -1.4195e+00
NGA-ADM2-72505758B15135669  4.5343e-01 -5.8659e-04  5.6205e-02  1.9151e+00
NGA-ADM2-72505758B15152925  1.5866e-01 -1.2418e-05  1.9123e-03  3.6285e+00
NGA-ADM2-72505758B15168871  4.1985e-01 -5.8659e-04  5.6205e-02  1.7734e+00
NGA-ADM2-72505758B15269567 -2.6156e-01 -2.7444e-04  2.3351e-02 -1.7099e+00
NGA-ADM2-72505758B15283345 -6.5138e-02 -5.4031e-05  6.9244e-03 -7.8214e-01
NGA-ADM2-72505758B15329511  1.9968e-03 -9.1702e-08  1.4122e-05  5.3138e-01
NGA-ADM2-72505758B15626765  4.4627e-01 -5.8659e-04  9.0281e-02  1.4872e+00
NGA-ADM2-72505758B15745475  1.6682e-01 -1.9733e-04  1.8914e-02  1.2144e+00
NGA-ADM2-72505758B15928088  8.6339e+00 -4.1790e-02  4.3932e+00  4.1391e+00
NGA-ADM2-72505758B1616690   3.1706e+00 -2.6376e-03  4.0511e-01  4.9856e+00
NGA-ADM2-72505758B16281923 -1.0863e-01 -9.7408e-05  1.4999e-02 -8.8618e-01
NGA-ADM2-72505758B16283774  4.5343e-01 -5.8659e-04  1.1300e-01  1.3506e+00
NGA-ADM2-72505758B16331092 -1.1025e-01 -4.9757e-04  6.3739e-02 -4.3471e-01
NGA-ADM2-72505758B16408752 -1.6556e-01 -9.7408e-05  1.2483e-02 -1.4809e+00
NGA-ADM2-72505758B16424915  1.9150e+00 -3.5961e-03  4.5924e-01  2.8312e+00
NGA-ADM2-72505758B16610760  4.5343e-01 -5.8659e-04  6.4318e-02  1.7902e+00
NGA-ADM2-72505758B16696559  4.9135e-01 -8.0641e-04  8.8402e-02  1.6553e+00
NGA-ADM2-72505758B16765159 -2.4029e-01 -4.1587e-04  3.9854e-02 -1.2016e+00
NGA-ADM2-72505758B16773759  4.5343e-01 -5.8659e-04  9.0281e-02  1.5110e+00
NGA-ADM2-72505758B17259178  1.4667e+00 -9.1874e-04  1.7692e-01  3.4891e+00
NGA-ADM2-72505758B17453237  1.7848e-02 -5.4031e-05  8.3202e-03  1.9626e-01
NGA-ADM2-72505758B17534332  4.5343e-01 -5.8659e-04  9.0281e-02  1.5110e+00
NGA-ADM2-72505758B17563771  4.5343e-01 -5.8659e-04  1.1300e-01  1.3506e+00
NGA-ADM2-72505758B17614134  1.7009e+00 -3.2601e-03  5.0042e-01  2.4091e+00
NGA-ADM2-72505758B17633838  1.1906e-03 -2.5869e-05  9.9982e-03  1.2166e-02
NGA-ADM2-72505758B17736122  1.8383e-01 -1.8759e-04  2.4037e-02  1.1869e+00
NGA-ADM2-72505758B1782277   3.8763e-03 -4.2752e-07  5.4793e-05  5.2373e-01
NGA-ADM2-72505758B18027142  4.4896e-01 -5.8659e-04  1.1300e-01  1.3373e+00
NGA-ADM2-72505758B18156007  4.5343e-01 -5.8659e-04  9.0281e-02  1.5110e+00
NGA-ADM2-72505758B18272004  1.0956e-01 -1.8759e-04  2.4037e-02  7.0783e-01
NGA-ADM2-72505758B1827434   1.8646e-02 -4.8993e-05  5.3749e-03  2.5500e-01
NGA-ADM2-72505758B18295427  5.5328e-01 -5.5762e-04  8.5825e-02  1.8905e+00
NGA-ADM2-72505758B18326272  9.2477e-01 -2.5474e-04  6.5536e-02  3.6134e+00
NGA-ADM2-72505758B18376242  2.5333e-01 -1.0446e-04  1.3387e-02  2.1904e+00
NGA-ADM2-72505758B18447698  2.7415e-01 -4.7092e-04  7.2486e-02  1.0200e+00
NGA-ADM2-72505758B18534598  5.1856e-01 -1.5148e-03  1.9385e-01  1.1812e+00
NGA-ADM2-72505758B18548676 -4.8099e-02 -2.0075e-05  3.0915e-03 -8.6471e-01
NGA-ADM2-72505758B18747813  4.4624e+00 -1.0222e-02  1.9502e+00  3.2028e+00
NGA-ADM2-72505758B18888506  4.5343e-01 -5.8659e-04  9.0281e-02  1.5110e+00
NGA-ADM2-72505758B18960886  3.2893e-02 -2.5869e-05  2.8381e-03  6.1791e-01
NGA-ADM2-72505758B19119765  2.2410e-01 -1.9733e-04  1.6791e-02  1.7309e+00
NGA-ADM2-72505758B19327087  4.5343e-01 -5.8659e-04  9.0281e-02  1.5110e+00
NGA-ADM2-72505758B19376786  1.0661e-01 -1.6230e-04  2.0797e-02  7.4040e-01
NGA-ADM2-72505758B19458752  2.3111e+00 -1.6602e-02  1.7912e+00  1.7392e+00
NGA-ADM2-72505758B19462210 -8.2286e-04 -1.5863e-06  2.4429e-04 -5.2546e-02
NGA-ADM2-72505758B19539344  8.4384e-02 -2.7444e-04  3.0101e-02  4.8795e-01
NGA-ADM2-72505758B196939    3.2588e+00 -1.8633e-02  2.8159e+00  1.9531e+00
NGA-ADM2-72505758B19914513  4.5343e-01 -5.8659e-04  1.5086e-01  1.1689e+00
NGA-ADM2-72505758B20050296  4.5088e-01 -5.8659e-04  6.4318e-02  1.7801e+00
NGA-ADM2-72505758B20351569  4.5343e-01 -5.8659e-04  7.5136e-02  1.6564e+00
NGA-ADM2-72505758B20421162  1.8881e-01 -3.4150e-04  1.3194e-01  5.2075e-01
NGA-ADM2-72505758B20535362  4.6822e-03 -4.2752e-07  6.5837e-05  5.7711e-01
NGA-ADM2-72505758B20542872  1.9848e-01 -3.0705e-04  5.9166e-02  8.1723e-01
NGA-ADM2-72505758B20606047 -4.2156e-02 -3.6516e-05  7.0382e-03 -5.0205e-01
NGA-ADM2-72505758B20675427  1.3542e-02 -1.5863e-06  1.3501e-04  1.1656e+00
NGA-ADM2-72505758B20849864  2.9483e-04 -9.1702e-08  1.4122e-05  7.8479e-02
NGA-ADM2-72505758B21150125  4.5343e-01 -5.8659e-04  7.5136e-02  1.6564e+00
NGA-ADM2-72505758B21444598  4.5343e-01 -5.8659e-04  5.6205e-02  1.9151e+00
NGA-ADM2-72505758B21552075  4.5812e+00 -3.7118e-03  4.0571e-01  7.1982e+00
NGA-ADM2-72505758B2169568   1.4966e-02 -6.5905e-06  1.0149e-03  4.7000e-01
NGA-ADM2-72505758B2190517   3.7568e-02 -2.7444e-04  5.2883e-02  1.6456e-01
NGA-ADM2-72505758B21920023  4.5343e-01 -5.8659e-04  4.9895e-02  2.0326e+00
NGA-ADM2-72505758B2204672   6.2843e+00 -1.8633e-02  2.0061e+00  4.4500e+00
NGA-ADM2-72505758B22226897  4.5343e-01 -5.8659e-04  7.5136e-02  1.6564e+00
NGA-ADM2-72505758B22346210  3.4331e-02 -6.5905e-06  1.0149e-03  1.0778e+00
NGA-ADM2-72505758B22432067  1.9683e-01 -5.4117e-04  5.1855e-02  8.6674e-01
NGA-ADM2-72505758B22509400  5.3270e-04 -1.1721e-04  2.2589e-02  4.3242e-03
NGA-ADM2-72505758B22625464  6.2100e-01 -1.1010e-03  1.0544e-01  1.9159e+00
NGA-ADM2-72505758B22711214  4.5343e-01 -5.8659e-04  9.0281e-02  1.5110e+00
NGA-ADM2-72505758B22775279  1.2945e-01 -2.7444e-04  5.2883e-02  5.6411e-01
NGA-ADM2-72505758B22890603  9.1903e-01 -6.5165e-04  1.6758e-01  2.2466e+00
NGA-ADM2-72505758B22914768  1.7971e-01 -4.1587e-04  6.4017e-02  7.1192e-01
NGA-ADM2-72505758B22969834  8.6775e-03 -7.9439e-05  1.5311e-02  7.0771e-02
NGA-ADM2-72505758B23063504  4.5343e-01 -5.8659e-04  7.5136e-02  1.6564e+00
NGA-ADM2-72505758B23284206  1.9468e-01 -5.4117e-04  5.9340e-02  8.0141e-01
NGA-ADM2-72505758B23339862  4.5343e-01 -5.8659e-04  5.6205e-02  1.9151e+00
NGA-ADM2-72505758B23406569  7.4582e-02 -1.6230e-04  2.4989e-02  4.7282e-01
NGA-ADM2-72505758B23525102  4.5343e-01 -5.8659e-04  9.0281e-02  1.5110e+00
NGA-ADM2-72505758B23727233  4.5343e-01 -5.8659e-04  7.5136e-02  1.6564e+00
NGA-ADM2-72505758B23758727 -2.6266e-03 -5.4031e-05  6.9244e-03 -3.0915e-02
NGA-ADM2-72505758B23938972  1.1005e-01 -2.7444e-04  7.0603e-02  4.1521e-01
NGA-ADM2-72505758B24068194 -4.1930e-03 -4.9114e-06  4.7087e-04 -1.9300e-01
NGA-ADM2-72505758B24079849  1.5220e-01 -3.0705e-04  3.3677e-02  8.3103e-01
NGA-ADM2-72505758B24173949  9.0976e-02 -1.7136e-04  1.8797e-02  6.6480e-01
NGA-ADM2-72505758B24287701 -2.7745e-01 -4.1587e-04  4.5607e-02 -1.2972e+00
NGA-ADM2-72505758B24946110  3.9970e-01 -5.8659e-04  9.0281e-02  1.3322e+00
NGA-ADM2-72505758B24975398  2.3957e+00 -7.1980e-03  6.8513e-01  2.9030e+00
NGA-ADM2-72505758B25108439  2.1590e+00 -9.8389e-03  1.8778e+00  1.5827e+00
NGA-ADM2-72505758B25110832  1.4782e-01 -3.4150e-04  6.5800e-02  5.7758e-01
NGA-ADM2-72505758B25204428  4.0866e-01 -5.8659e-04  7.5136e-02  1.4930e+00
NGA-ADM2-72505758B25323941  2.1532e-01 -5.4117e-04  8.3293e-02  7.4796e-01
NGA-ADM2-72505758B25363477  3.7206e-01 -1.7136e-04  1.6426e-02  2.9043e+00
NGA-ADM2-72505758B25708171  0.0000e+00  0.0000e+00  0.0000e+00         NaN
NGA-ADM2-72505758B26082732  6.0650e-03 -6.3301e-05  6.9445e-03  7.3540e-02
NGA-ADM2-72505758B26198977  2.4841e-01 -7.0140e-04  2.7090e-01  4.7861e-01
NGA-ADM2-72505758B26243068  4.5343e-01 -5.8659e-04  1.5086e-01  1.1689e+00
NGA-ADM2-72505758B2628120   4.5343e-01 -5.8659e-04  1.1300e-01  1.3506e+00
NGA-ADM2-72505758B26346364  4.5343e-01 -5.8659e-04  5.6205e-02  1.9151e+00
NGA-ADM2-72505758B26429015  1.3991e-01 -2.8619e-04  2.1887e-02  9.4764e-01
NGA-ADM2-72505758B26523677  4.5343e-01 -5.8659e-04  1.1300e-01  1.3506e+00
NGA-ADM2-72505758B26556107 -1.9482e-02 -1.1721e-04  2.2589e-02 -1.2885e-01
NGA-ADM2-72505758B2657339   4.5343e-01 -5.8659e-04  6.4318e-02  1.7902e+00
NGA-ADM2-72505758B26581542  1.3723e+01 -7.8938e-02  5.0496e+00  6.1419e+00
NGA-ADM2-72505758B27276798  4.5343e-01 -5.8659e-04  7.5136e-02  1.6564e+00
NGA-ADM2-72505758B27408614  2.4376e+00 -2.6376e-03  3.3715e-01  4.2027e+00
NGA-ADM2-72505758B2745087  -2.3226e-02 -5.4117e-04  4.6033e-02 -1.0573e-01
NGA-ADM2-72505758B27539273  4.5343e-01 -5.8659e-04  7.5136e-02  1.6564e+00
NGA-ADM2-72505758B27542400 -7.4060e-03 -4.2752e-07  4.0987e-05 -1.1567e+00
NGA-ADM2-72505758B2760907  -4.9211e-02 -2.5869e-05  3.9837e-03 -7.7927e-01
NGA-ADM2-72505758B27615672  4.0698e-01 -2.3510e-03  3.0061e-01  7.4657e-01
NGA-ADM2-72505758B27700910  4.2299e-01 -5.8659e-04  4.4847e-02  2.0002e+00
NGA-ADM2-72505758B27714394  1.4054e-02 -1.7053e-05  1.8709e-03  3.2532e-01
NGA-ADM2-72505758B27717699 -2.5707e-03 -4.2752e-07  4.6904e-05 -3.7529e-01
NGA-ADM2-72505758B27989153  4.5343e-01 -5.8659e-04  5.6205e-02  1.9151e+00
NGA-ADM2-72505758B28102942 -4.4581e-01 -1.1721e-04  4.5295e-02 -2.0941e+00
NGA-ADM2-72505758B28219123  3.4616e+00 -3.5961e-03  3.4353e-01  5.9122e+00
NGA-ADM2-72505758B28322663  4.5343e-01 -5.8659e-04  9.0281e-02  1.5110e+00
NGA-ADM2-72505758B28358277  4.5343e-01 -5.8659e-04  9.0281e-02  1.5110e+00
NGA-ADM2-72505758B28448754  2.2229e-01 -7.0140e-04  5.9654e-02  9.1301e-01
NGA-ADM2-72505758B28451778  3.7374e-01 -1.0384e-03  1.3295e-01  1.0279e+00
NGA-ADM2-72505758B28517619  6.1152e-01 -2.2592e-03  2.4730e-01  1.2342e+00
NGA-ADM2-72505758B28558302  4.5402e-02 -6.3301e-05  9.7476e-03  4.6050e-01
NGA-ADM2-72505758B28564088  4.5343e-01 -5.8659e-04  7.5136e-02  1.6564e+00
NGA-ADM2-72505758B28688505  4.5343e-01 -5.8659e-04  1.1300e-01  1.3506e+00
NGA-ADM2-72505758B28779634  2.6287e-02 -2.0075e-05  3.8694e-03  4.2291e-01
NGA-ADM2-72505758B28994882  4.5343e-01 -5.8659e-04  1.5086e-01  1.1689e+00
NGA-ADM2-72505758B29272053  3.9968e-02 -2.5938e-06  2.4867e-04  2.5347e+00
NGA-ADM2-72505758B29476596  1.7014e-01 -2.7444e-04  3.0101e-02  9.8223e-01
NGA-ADM2-72505758B29578266  7.9042e-01 -3.9154e-04  1.0072e-01  2.4919e+00
NGA-ADM2-72505758B29634978  4.5343e-01 -5.8659e-04  1.1300e-01  1.3506e+00
NGA-ADM2-72505758B29748439  1.9154e-02 -1.2418e-05  1.5915e-03  4.8044e-01
NGA-ADM2-72505758B29886865 -2.8900e-02 -2.5869e-05  2.8381e-03 -5.4199e-01
NGA-ADM2-72505758B30062209  4.5343e-01 -5.8659e-04  1.1300e-01  1.3506e+00
NGA-ADM2-72505758B30286847  4.5343e-01 -5.8659e-04  1.1300e-01  1.3506e+00
NGA-ADM2-72505758B30316327 -4.7296e-01 -3.7777e-04  3.2139e-02 -2.6361e+00
NGA-ADM2-72505758B30341250 -3.1519e-02 -6.5905e-06  7.2305e-04 -1.1719e+00
NGA-ADM2-72505758B30347581  4.5343e-01 -5.8659e-04  5.6205e-02  1.9151e+00
NGA-ADM2-72505758B30546335  2.9867e+00 -4.8350e-03  7.4098e-01  3.4753e+00
NGA-ADM2-72505758B30682486  4.5343e-01 -5.8659e-04  4.9895e-02  2.0326e+00
NGA-ADM2-72505758B3073896  -9.0178e-02 -1.0067e-05  1.9404e-03 -2.0470e+00
NGA-ADM2-72505758B3096768   4.5343e-01 -5.8659e-04  4.9895e-02  2.0326e+00
NGA-ADM2-72505758B31033090  1.6172e-02 -1.6230e-04  2.4989e-02  1.0333e-01
NGA-ADM2-72505758B31054894  1.2823e-01 -1.3884e-04  2.1378e-02  8.7799e-01
NGA-ADM2-72505758B31195973  4.5343e-01 -5.8659e-04  4.9895e-02  2.0326e+00
NGA-ADM2-72505758B31206848  1.0732e-01 -1.3884e-04  1.3309e-02  9.3148e-01
NGA-ADM2-72505758B31230586  5.1848e+00 -4.5726e-03  7.0095e-01  6.1983e+00
NGA-ADM2-72505758B31246828  3.0012e-02 -1.2418e-05  1.5915e-03  7.5262e-01
NGA-ADM2-72505758B31287755  4.5343e-01 -5.8659e-04  1.1300e-01  1.3506e+00
NGA-ADM2-72505758B31299772  1.0956e-01 -1.8759e-04  2.4037e-02  7.0783e-01
NGA-ADM2-72505758B31351375  6.7143e-02 -2.4366e-04  4.6953e-02  3.1098e-01
NGA-ADM2-72505758B31542029  1.5972e-01 -4.5581e-04  7.0161e-02  6.0472e-01
NGA-ADM2-72505758B31597260  4.0196e+00 -3.9486e-03  2.7315e-01  7.6986e+00
NGA-ADM2-72505758B31818357  4.5343e-01 -5.8659e-04  7.5136e-02  1.6564e+00
NGA-ADM2-72505758B31818553  4.5343e-01 -5.8659e-04  7.5136e-02  1.6564e+00
NGA-ADM2-72505758B3188194   5.6276e-02 -4.8993e-05  4.1696e-03  8.7228e-01
NGA-ADM2-72505758B31996608  3.8282e-02 -3.6516e-05  7.0382e-03  4.5675e-01
NGA-ADM2-72505758B32139672  1.3708e+00 -2.9406e-03  5.6513e-01  1.8274e+00
NGA-ADM2-72505758B32177909 -4.1481e-02 -2.9563e-05  3.2434e-03 -7.2786e-01
NGA-ADM2-72505758B32188730  1.4344e-01 -1.9733e-04  1.8914e-02  1.0444e+00
NGA-ADM2-72505758B32218397  4.5343e-01 -5.8659e-04  1.1300e-01  1.3506e+00
NGA-ADM2-72505758B32330173  4.4896e-01 -5.8659e-04  1.1300e-01  1.3373e+00
NGA-ADM2-72505758B32419485  4.5343e-01 -5.8659e-04  5.6205e-02  1.9151e+00
NGA-ADM2-72505758B32554889  3.0478e-01 -5.4117e-04  8.3293e-02  1.0579e+00
NGA-ADM2-72505758B32611817  8.1494e-01 -3.8292e-03  3.6571e-01  1.3539e+00
NGA-ADM2-72505758B32630687 -3.6920e-02 -9.7408e-05  9.3379e-03 -3.8106e-01
NGA-ADM2-72505758B32774266  4.5343e-01 -5.8659e-04  6.4318e-02  1.7902e+00
NGA-ADM2-72505758B32794130  1.3640e-01 -2.4366e-04  4.6953e-02  6.3062e-01
NGA-ADM2-72505758B32949816  4.5343e-01 -5.8659e-04  6.4318e-02  1.7902e+00
NGA-ADM2-72505758B3304967   4.5343e-01 -5.8659e-04  6.4318e-02  1.7902e+00
NGA-ADM2-72505758B33054765  7.6715e+00 -2.7609e-02  2.5738e+00  4.7990e+00
NGA-ADM2-72505758B33108582  4.3552e-01 -5.4117e-04  5.1855e-02  1.9149e+00
NGA-ADM2-72505758B3317503   3.6579e+00 -4.7029e-03  3.9838e-01  5.8028e+00
NGA-ADM2-72505758B33219881  4.5343e-01 -5.8659e-04  6.4318e-02  1.7902e+00
NGA-ADM2-72505758B33244779 -2.1214e-02 -1.2493e-04  2.4077e-02 -1.3591e-01
NGA-ADM2-72505758B33343517  1.5034e-01 -3.7777e-04  4.1430e-02  7.4045e-01
NGA-ADM2-72505758B33542533  5.0273e-02 -9.7408e-05  1.0686e-02  4.8727e-01
NGA-ADM2-72505758B33577737  9.6220e-03 -2.1471e-04  2.3551e-02  6.4098e-02
NGA-ADM2-72505758B3369984   1.1980e-01 -1.6230e-04  2.4989e-02  7.5889e-01
NGA-ADM2-72505758B34009830  4.5343e-01 -5.8659e-04  1.1300e-01  1.3506e+00
NGA-ADM2-72505758B34036858  9.3746e-01 -5.5762e-04  1.0742e-01  2.8620e+00
NGA-ADM2-72505758B34194291  4.5343e-01 -5.8659e-04  1.1300e-01  1.3506e+00
NGA-ADM2-72505758B34380318  2.2118e+00 -3.4823e-03  4.4475e-01  3.3217e+00
NGA-ADM2-72505758B34441411  4.5343e-01 -5.8659e-04  1.5086e-01  1.1689e+00
NGA-ADM2-72505758B34494634  8.0853e-01 -1.9101e-03  4.9058e-01  1.1571e+00
NGA-ADM2-72505758B34508441  4.5343e-01 -5.8659e-04  1.1300e-01  1.3506e+00
NGA-ADM2-72505758B34643703  4.4985e-01 -5.8659e-04  9.0281e-02  1.4991e+00
NGA-ADM2-72505758B34822167  1.4140e+00 -8.7331e-03  7.3677e-01  1.6575e+00
NGA-ADM2-72505758B34881213  4.5343e-01 -5.8659e-04  1.1300e-01  1.3506e+00
NGA-ADM2-72505758B35176966  1.7771e-01 -2.2512e-04  2.8846e-02  1.0477e+00
NGA-ADM2-72505758B35597270  4.4149e-01 -5.8659e-04  4.9895e-02  1.9791e+00
NGA-ADM2-72505758B35626837  4.5343e-01 -5.8659e-04  7.5136e-02  1.6564e+00
NGA-ADM2-72505758B35748968  4.5343e-01 -5.8659e-04  1.5086e-01  1.1689e+00
NGA-ADM2-72505758B35936626  4.5343e-01 -5.8659e-04  4.9895e-02  2.0326e+00
NGA-ADM2-72505758B36147146 -1.6758e-03 -9.1702e-08  1.4122e-05 -4.4593e-01
NGA-ADM2-72505758B3618695  -1.8805e-01 -2.7444e-04  3.5164e-02 -1.0014e+00
NGA-ADM2-72505758B36277624  1.1788e-01 -4.1587e-04  8.0125e-02  4.1791e-01
NGA-ADM2-72505758B36341125  4.5343e-01 -5.8659e-04  6.4318e-02  1.7902e+00
NGA-ADM2-72505758B36411974  4.5343e-01 -5.8659e-04  9.0281e-02  1.5110e+00
NGA-ADM2-72505758B36631288  4.5343e-01 -5.8659e-04  9.0281e-02  1.5110e+00
NGA-ADM2-72505758B36739173  2.7200e+00 -2.9406e-03  3.2167e-01  4.8009e+00
NGA-ADM2-72505758B36818221 -8.1603e-02 -3.1948e-04  3.5039e-02 -4.3424e-01
NGA-ADM2-72505758B36829366  4.0368e-01 -5.8659e-04  4.9895e-02  1.8099e+00
NGA-ADM2-72505758B36860554  6.9785e-02 -1.1721e-04  1.8048e-02  5.2034e-01
NGA-ADM2-72505758B36958634 -4.7282e-02 -4.9114e-06  6.2946e-04 -1.8844e+00
NGA-ADM2-72505758B37006139  1.0904e+00 -4.3031e-04  6.6239e-02  4.2386e+00
NGA-ADM2-72505758B37235287  4.5343e-01 -5.8659e-04  4.9895e-02  2.0326e+00
NGA-ADM2-72505758B3729824  -3.7128e-02 -2.0075e-05  1.7085e-03 -8.9775e-01
NGA-ADM2-72505758B37546318  6.3720e-01 -2.8619e-04  5.5148e-02  2.7146e+00
NGA-ADM2-72505758B37687991  4.5343e-01 -5.8659e-04  9.0281e-02  1.5110e+00
NGA-ADM2-72505758B3771557   1.2230e-01 -2.7444e-04  7.0603e-02  4.6132e-01
NGA-ADM2-72505758B37718139  4.0308e-02 -2.5869e-05  1.9789e-03  9.0669e-01
NGA-ADM2-72505758B38224950 -4.6041e-02 -3.1948e-04  4.0933e-02 -2.2599e-01
NGA-ADM2-72505758B3838497   4.2556e+00 -2.3510e-03  4.5209e-01  6.3327e+00
NGA-ADM2-72505758B38387184  4.5343e-01 -5.8659e-04  7.5136e-02  1.6564e+00
NGA-ADM2-72505758B38470188  4.5343e-01 -5.8659e-04  9.0281e-02  1.5110e+00
NGA-ADM2-72505758B38532832  4.5120e-01 -5.8659e-04  5.6205e-02  1.9056e+00
NGA-ADM2-72505758B38565081  2.1296e-01 -3.7777e-04  3.6204e-02  1.1212e+00
NGA-ADM2-72505758B38716464  4.5291e-02 -9.7408e-05  8.2895e-03  4.9852e-01
NGA-ADM2-72505758B38827784 -3.9162e-02 -8.5820e-05  6.5645e-03 -4.8230e-01
NGA-ADM2-72505758B38868411  4.5343e-01 -5.8659e-04  7.5136e-02  1.6564e+00
NGA-ADM2-72505758B38957187 -1.9003e-01 -1.3884e-04  1.3309e-02 -1.6460e+00
NGA-ADM2-72505758B38976800  1.1379e+00 -8.0641e-04  7.7250e-02  4.0968e+00
NGA-ADM2-72505758B38989055  1.5106e+00 -3.0453e-03  7.8126e-01  1.7125e+00
NGA-ADM2-72505758B39059766  2.3098e-01 -4.1587e-04  6.4017e-02  9.1457e-01
NGA-ADM2-72505758B39110166  1.6505e-01 -4.0882e-05  3.4793e-03  2.7988e+00
NGA-ADM2-72505758B39194027  4.4746e-01 -5.8659e-04  1.5086e-01  1.1536e+00
NGA-ADM2-72505758B39432389  6.0909e-03 -4.9114e-06  7.5634e-04  2.2165e-01
NGA-ADM2-72505758B39446185  4.5343e-01 -5.8659e-04  1.1300e-01  1.3506e+00
NGA-ADM2-72505758B39689947  4.5343e-01 -5.8659e-04  9.0281e-02  1.5110e+00
NGA-ADM2-72505758B40149693  1.3736e+00 -2.3510e-03  2.2487e-01  2.9016e+00
NGA-ADM2-72505758B40157454  3.3178e+00 -3.9486e-03  4.3149e-01  5.0568e+00
NGA-ADM2-72505758B40428434  4.5343e-01 -5.8659e-04  9.0281e-02  1.5110e+00
NGA-ADM2-72505758B40532579 -1.0827e-04 -9.1702e-08  1.4122e-05 -2.8786e-02
NGA-ADM2-72505758B40651914  7.0885e-05 -9.1702e-08  1.0061e-05  2.2377e-02
NGA-ADM2-72505758B40667848  4.5144e-01 -5.8659e-04  4.9895e-02  2.0237e+00
NGA-ADM2-72505758B40714647  4.1871e-02 -6.3301e-05  9.7476e-03  4.2474e-01
NGA-ADM2-72505758B40744784  1.0829e+00 -1.0222e-02  1.5581e+00  8.7573e-01
NGA-ADM2-72505758B40746170  4.0567e-01 -5.8659e-04  7.5136e-02  1.4821e+00
NGA-ADM2-72505758B40877575  4.5574e-02 -2.5869e-05  3.9837e-03  7.2246e-01
NGA-ADM2-72505758B40987774  8.8575e-02 -1.8759e-04  2.0577e-02  6.1879e-01
NGA-ADM2-72505758B41151402  4.5343e-01 -5.8659e-04  1.1300e-01  1.3506e+00
NGA-ADM2-72505758B41263993  1.2039e-01 -1.3884e-04  2.6757e-02  7.3685e-01
NGA-ADM2-72505758B41363947  4.5343e-01 -5.8659e-04  5.6205e-02  1.9151e+00
NGA-ADM2-72505758B41458967  7.0319e-01 -2.8378e-03  3.6267e-01  1.1724e+00
NGA-ADM2-72505758B41522993  2.4522e-01 -5.4031e-05  5.9275e-03  3.1858e+00
NGA-ADM2-72505758B41606003 -4.8317e-02 -2.9563e-05  2.2615e-03 -1.0154e+00
NGA-ADM2-72505758B41747981  4.5343e-01 -5.8659e-04  7.5136e-02  1.6564e+00
NGA-ADM2-72505758B41820351  4.5343e-01 -5.8659e-04  7.5136e-02  1.6564e+00
NGA-ADM2-72505758B41923004  5.3401e-02 -4.8993e-05  6.2789e-03  6.7453e-01
NGA-ADM2-72505758B41928930  1.6910e-01 -2.8619e-04  3.6669e-02  8.8456e-01
NGA-ADM2-72505758B41934932  4.6990e-03 -9.1702e-08  1.1753e-05  1.3707e+00
NGA-ADM2-72505758B41955915  3.9210e-03 -8.5820e-05  7.3034e-03  4.6886e-02
NGA-ADM2-72505758B4198149   1.5141e-01 -2.4366e-04  3.7514e-02  7.8299e-01
NGA-ADM2-72505758B42001588  4.5343e-01 -5.8659e-04  2.2658e-01  9.5381e-01
NGA-ADM2-72505758B42014722  4.5343e-01 -5.8659e-04  5.6205e-02  1.9151e+00
NGA-ADM2-72505758B42099323  4.5343e-01 -5.8659e-04  1.1300e-01  1.3506e+00
NGA-ADM2-72505758B42200288  4.5343e-01 -5.8659e-04  6.4318e-02  1.7902e+00
NGA-ADM2-72505758B42248280  6.1124e+00 -5.9579e-03  9.1204e-01  6.4066e+00
NGA-ADM2-72505758B42260172 -6.2259e-01 -4.1587e-04  6.4017e-02 -2.4590e+00
NGA-ADM2-72505758B42412373  4.5343e-01 -5.8659e-04  6.4318e-02  1.7902e+00
NGA-ADM2-72505758B42533808  1.5269e-02 -4.9114e-06  4.1800e-04  7.4705e-01
NGA-ADM2-72505758B42614095  4.5343e-01 -5.8659e-04  9.0281e-02  1.5110e+00
NGA-ADM2-72505758B4268401   1.2316e+00 -1.7465e-03  2.2344e-01  2.6091e+00
NGA-ADM2-72505758B42691841  1.1277e-01 -2.7444e-04  2.3351e-02  7.3980e-01
NGA-ADM2-72505758B42781808  5.5374e-02 -1.1721e-04  1.8048e-02  4.1306e-01
NGA-ADM2-72505758B42822246 -2.6142e-02 -1.9733e-04  3.0382e-02 -1.4885e-01
NGA-ADM2-72505758B43208251  2.3741e-02 -2.5938e-06  4.9995e-04  1.0619e+00
NGA-ADM2-72505758B43213978 -5.7511e-02 -1.1721e-04  2.2589e-02 -3.8188e-01
NGA-ADM2-72505758B43516104  3.4012e-01 -6.5165e-04  1.6758e-01  8.3243e-01
NGA-ADM2-72505758B43671176  2.4348e-01 -3.4150e-04  3.2729e-02  1.3477e+00
NGA-ADM2-72505758B4371453   5.9002e-01 -6.5165e-04  7.1447e-02  2.2098e+00
NGA-ADM2-72505758B43939903  4.5343e-01 -5.8659e-04  6.4318e-02  1.7902e+00
NGA-ADM2-72505758B43980846  4.5343e-01 -5.8659e-04  7.5136e-02  1.6564e+00
NGA-ADM2-72505758B44064464 -1.4817e-01 -6.3301e-05  8.1125e-03 -1.6444e+00
NGA-ADM2-72505758B44073392 -2.6395e-02 -1.4723e-04  1.4113e-02 -2.2094e-01
NGA-ADM2-72505758B4407900  -1.2146e-03 -1.7053e-05  1.8709e-03 -2.7688e-02
NGA-ADM2-72505758B44145348 -1.2661e-01 -3.7777e-04  3.6204e-02 -6.6341e-01
NGA-ADM2-72505758B44194354  4.5343e-01 -5.8659e-04  1.1300e-01  1.3506e+00
NGA-ADM2-72505758B44226036  1.4190e+00 -8.2049e-03  1.0430e+00  1.3975e+00
NGA-ADM2-72505758B44240493  9.2697e-02 -2.7444e-04  5.2883e-02  4.0429e-01
NGA-ADM2-72505758B44273667  7.8544e-02 -7.9439e-05  1.2233e-02  7.1087e-01
NGA-ADM2-72505758B44395382 -1.4795e-02 -2.5869e-05  4.9861e-03 -2.0916e-01
NGA-ADM2-72505758B44548256  4.2782e-01 -1.9733e-04  3.8027e-02  2.1949e+00
NGA-ADM2-72505758B44695959  4.5343e-01 -5.8659e-04  6.4318e-02  1.7902e+00
NGA-ADM2-72505758B44831066  4.7586e-01 -8.5820e-05  7.3034e-03  5.5692e+00
NGA-ADM2-72505758B44941782  6.3362e-01 -4.7092e-04  7.2486e-02  2.3552e+00
NGA-ADM2-72505758B45015575  4.0194e-01 -5.8659e-04  5.6205e-02  1.6979e+00
NGA-ADM2-72505758B45047614  1.1664e+00 -4.7092e-04  9.0726e-02  3.8740e+00
NGA-ADM2-72505758B4505528   2.0511e-02 -1.7053e-05  2.6261e-03  4.0059e-01
NGA-ADM2-72505758B45148365  4.5343e-01 -5.8659e-04  9.0281e-02  1.5110e+00
NGA-ADM2-72505758B45209095 -3.7701e-02 -4.8993e-05  7.5445e-03 -4.3348e-01
NGA-ADM2-72505758B45319201  4.5343e-01 -5.8659e-04  9.0281e-02  1.5110e+00
NGA-ADM2-72505758B4532539   4.5343e-01 -5.8659e-04  7.5136e-02  1.6564e+00
NGA-ADM2-72505758B45363429  1.4053e-01 -1.6230e-04  2.4989e-02  8.9000e-01
NGA-ADM2-72505758B45556353  1.7018e-01 -4.9757e-04  7.6587e-02  6.1673e-01
NGA-ADM2-72505758B45800050 -1.0404e-01 -6.3301e-05  1.6288e-02 -8.1473e-01
NGA-ADM2-72505758B4580856   1.1997e+00 -9.7765e-04  1.5041e-01  3.0959e+00
NGA-ADM2-72505758B45966975  4.5343e-01 -5.8659e-04  1.1300e-01  1.3506e+00
NGA-ADM2-72505758B46314370  2.7445e+00 -2.3510e-03  2.5733e-01  5.4149e+00
NGA-ADM2-72505758B46349170  1.1680e-01 -4.1587e-04  4.5607e-02  5.4888e-01
NGA-ADM2-72505758B4635888  -4.5954e-02 -3.6516e-05  5.6232e-03 -6.1233e-01
NGA-ADM2-72505758B46467475 -6.7693e-02 -4.0882e-05  5.2394e-03 -9.3464e-01
NGA-ADM2-72505758B46624629 -1.9395e-03 -4.9114e-06  9.4666e-04 -6.2879e-02
NGA-ADM2-72505758B46727460 -1.3346e-01 -6.3301e-05  9.7476e-03 -1.3511e+00
NGA-ADM2-72505758B46745149  3.5198e-01 -1.9733e-04  3.0382e-02  2.0205e+00
NGA-ADM2-72505758B46906771 -8.3884e-02 -5.8659e-04  9.0281e-02 -2.7722e-01
NGA-ADM2-72505758B46945820  1.3107e+00 -9.7765e-04  1.8826e-01  3.0230e+00
NGA-ADM2-72505758B47092163  5.2907e-01 -2.0810e-03  4.0027e-01  8.3955e-01
NGA-ADM2-72505758B47276571  1.4248e+00 -1.6674e-03  3.2086e-01  2.5183e+00
NGA-ADM2-72505758B47502716  1.2231e-01 -1.6230e-04  4.1757e-02  5.9936e-01
NGA-ADM2-72505758B47558893  4.4985e-01 -5.8659e-04  9.0281e-02  1.4991e+00
NGA-ADM2-72505758B47569121  7.0142e+00 -4.3175e-03  1.1062e+00  6.6730e+00
NGA-ADM2-72505758B47597427  4.5343e-01 -5.8659e-04  7.5136e-02  1.6564e+00
NGA-ADM2-72505758B47868503  4.5343e-01 -5.8659e-04  9.0281e-02  1.5110e+00
NGA-ADM2-72505758B47972472  3.1826e-01 -7.5299e-04  7.2137e-02  1.1878e+00
NGA-ADM2-72505758B48054636  2.2393e-02 -2.1471e-04  4.1376e-02  1.1114e-01
NGA-ADM2-72505758B48100225  5.2358e-02 -9.7408e-05  1.0686e-02  5.0744e-01
NGA-ADM2-72505758B48120393  2.4629e-01 -5.4117e-04  1.0425e-01  7.6446e-01
NGA-ADM2-72505758B48161598  4.5343e-01 -5.8659e-04  4.9895e-02  2.0326e+00
NGA-ADM2-72505758B48168473  2.5028e-02 -6.5905e-06  8.4466e-04  8.6140e-01
NGA-ADM2-72505758B48317000  4.5343e-01 -5.8659e-04  1.5086e-01  1.1689e+00
NGA-ADM2-72505758B485966    1.5372e-01 -2.4366e-04  3.7514e-02  7.9491e-01
NGA-ADM2-72505758B48644703  4.5343e-01 -5.8659e-04  9.0281e-02  1.5110e+00
NGA-ADM2-72505758B48817484  4.5343e-01 -5.8659e-04  1.1300e-01  1.3506e+00
NGA-ADM2-72505758B48854878  7.2467e-02 -1.3884e-04  1.7791e-02  5.4433e-01
NGA-ADM2-72505758B48978893  4.5343e-01 -5.8659e-04  6.4318e-02  1.7902e+00
NGA-ADM2-72505758B48991596 -6.9521e-02 -1.1721e-04  2.2589e-02 -4.6178e-01
NGA-ADM2-72505758B49088403  4.5343e-01 -5.8659e-04  7.5136e-02  1.6564e+00
NGA-ADM2-72505758B49090421 -1.8028e-02 -1.0067e-05  1.5503e-03 -4.5762e-01
NGA-ADM2-72505758B49591931  3.6746e-01 -5.8659e-04  9.0281e-02  1.2249e+00
NGA-ADM2-72505758B49639858 -1.7493e-01 -1.1721e-04  1.5020e-02 -1.4264e+00
NGA-ADM2-72505758B49756103  4.3836e-02 -1.3884e-04  1.5230e-02  3.5633e-01
NGA-ADM2-72505758B49835051  4.5343e-01 -5.8659e-04  6.4318e-02  1.7902e+00
NGA-ADM2-72505758B49932072  3.0269e+00 -6.7193e-03  1.2864e+00  2.6746e+00
NGA-ADM2-72505758B50036017  5.1285e-02 -6.3301e-05  9.7476e-03  5.2009e-01
NGA-ADM2-72505758B50480947  6.6680e-02 -7.9439e-05  1.2233e-02  6.0360e-01
NGA-ADM2-72505758B50499057  4.5343e-01 -5.8659e-04  1.1300e-01  1.3506e+00
NGA-ADM2-72505758B50500527  4.5343e-01 -5.8659e-04  9.0281e-02  1.5110e+00
NGA-ADM2-72505758B50566658  4.7266e-02 -1.2418e-05  8.6242e-04  1.6099e+00
NGA-ADM2-72505758B50825869  4.5343e-01 -5.8659e-04  1.1300e-01  1.3506e+00
NGA-ADM2-72505758B5084877   3.3791e-01 -2.0810e-03  2.6615e-01  6.5903e-01
NGA-ADM2-72505758B50871717  1.7930e+00 -1.7465e-03  4.4864e-01  2.6795e+00
NGA-ADM2-72505758B5090387   4.5343e-01 -5.8659e-04  6.4318e-02  1.7902e+00
NGA-ADM2-72505758B50946056  1.3673e+00 -1.2316e-03  1.5765e-01  3.4466e+00
NGA-ADM2-72505758B51199259  7.6999e-02 -1.8759e-04  2.0577e-02  5.3809e-01
NGA-ADM2-72505758B5121987  -1.2241e-01 -3.7777e-04  4.8398e-02 -5.5472e-01
NGA-ADM2-72505758B51332829 -6.0110e-02 -3.5459e-04  1.3700e-01 -1.6144e-01
NGA-ADM2-72505758B51610317  1.3460e-01 -3.1948e-04  1.2344e-01  3.8403e-01
NGA-ADM2-72505758B5164375   4.5343e-01 -5.8659e-04  9.0281e-02  1.5110e+00
NGA-ADM2-72505758B51901764 -9.1926e-02 -2.1471e-04  3.3057e-02 -5.0442e-01
NGA-ADM2-72505758B51902603  1.4828e-01 -3.7777e-04  5.8154e-02  6.1646e-01
NGA-ADM2-72505758B52057503  1.4792e-01 -4.0882e-05  6.2955e-03  1.8648e+00
NGA-ADM2-72505758B52690633  2.2048e-01 -5.4117e-04  6.9321e-02  8.3948e-01
NGA-ADM2-72505758B52856855 -2.5154e-02 -1.8759e-04  2.8883e-02 -1.4690e-01
NGA-ADM2-72505758B528653    4.5343e-01 -5.8659e-04  1.1300e-01  1.3506e+00
NGA-ADM2-72505758B52884892  4.5343e-01 -5.8659e-04  2.2658e-01  9.5381e-01
NGA-ADM2-72505758B53166523  6.9954e-02 -2.9563e-05  3.2434e-03  1.2288e+00
NGA-ADM2-72505758B53799809  1.4294e-01 -3.0705e-04  3.3677e-02  7.8059e-01
NGA-ADM2-72505758B53984624  9.4534e-02 -2.7444e-04  4.2252e-02  4.6124e-01
NGA-ADM2-72505758B54152816  4.5343e-01 -5.8659e-04  7.5136e-02  1.6564e+00
NGA-ADM2-72505758B54320674  4.5343e-01 -5.8659e-04  1.1300e-01  1.3506e+00
NGA-ADM2-72505758B54394765  2.1071e-01 -1.9733e-04  1.5092e-02  1.7168e+00
NGA-ADM2-72505758B54495757 -4.5438e-03 -3.6516e-05  4.6799e-03 -6.5887e-02
NGA-ADM2-72505758B54638889  4.5088e-01 -5.8659e-04  6.4318e-02  1.7801e+00
NGA-ADM2-72505758B54686951  4.5343e-01 -5.8659e-04  5.6205e-02  1.9151e+00
NGA-ADM2-72505758B54729887  6.1371e-02 -2.4366e-04  3.7514e-02  3.1812e-01
NGA-ADM2-72505758B54838860  4.5343e-01 -5.8659e-04  7.5136e-02  1.6564e+00
NGA-ADM2-72505758B54904664  1.9327e-01 -4.9757e-04  7.6587e-02  7.0018e-01
NGA-ADM2-72505758B55254312  4.5120e-01 -5.8659e-04  5.6205e-02  1.9056e+00
NGA-ADM2-72505758B55275980  1.9409e-01 -3.1948e-04  6.1559e-02  7.8354e-01
NGA-ADM2-72505758B55501663  3.7703e-01 -5.4117e-04  8.3293e-02  1.3083e+00
NGA-ADM2-72505758B5575139   9.2479e-02 -7.9439e-05  8.7148e-03  9.9149e-01
NGA-ADM2-72505758B5578796   4.5343e-01 -5.8659e-04  1.5086e-01  1.1689e+00
NGA-ADM2-72505758B5592240   4.5343e-01 -5.8659e-04  7.5136e-02  1.6564e+00
NGA-ADM2-72505758B56024064  4.5343e-01 -5.8659e-04  9.0281e-02  1.5110e+00
NGA-ADM2-72505758B56032953  4.4985e-01 -5.8659e-04  9.0281e-02  1.4991e+00
NGA-ADM2-72505758B56149510  1.6927e-02 -1.5863e-06  1.7404e-04  1.2832e+00
NGA-ADM2-72505758B5623512   4.4597e-02 -3.0705e-04  2.9429e-02  2.6175e-01
NGA-ADM2-72505758B56331112  4.5343e-01 -5.8659e-04  6.4318e-02  1.7902e+00
NGA-ADM2-72505758B5637778   4.5343e-01 -5.8659e-04  9.0281e-02  1.5110e+00
NGA-ADM2-72505758B56394634  4.5343e-01 -5.8659e-04  9.0281e-02  1.5110e+00
NGA-ADM2-72505758B56444221  4.4448e-01 -5.8659e-04  7.5136e-02  1.6237e+00
NGA-ADM2-72505758B56744751  2.2452e-01 -4.0882e-05  6.2955e-03  2.8302e+00
NGA-ADM2-72505758B56799054  2.1834e-02 -1.7053e-05  2.1855e-03  4.6741e-01
NGA-ADM2-72505758B56816258  4.5343e-01 -5.8659e-04  5.6205e-02  1.9151e+00
NGA-ADM2-72505758B56925175 -2.0036e-01 -1.9946e-03  3.8369e-01 -3.2024e-01
NGA-ADM2-72505758B56934856  1.0863e-01 -2.8619e-04  5.5148e-02  4.6382e-01
NGA-ADM2-72505758B56955836  1.9989e-01 -2.7444e-04  4.2252e-02  9.7380e-01
NGA-ADM2-72505758B57073987  4.5343e-01 -5.8659e-04  1.5086e-01  1.1689e+00
NGA-ADM2-72505758B5716143   4.3552e-01 -5.4117e-04  1.3918e-01  1.1688e+00
NGA-ADM2-72505758B57235084  2.1057e-01 -3.7777e-04  9.7175e-02  6.7669e-01
NGA-ADM2-72505758B57280378 -9.9667e-02 -4.8993e-05  5.3749e-03 -1.3588e+00
NGA-ADM2-72505758B57306951  3.2898e-02 -3.0705e-04  2.6125e-02  2.0544e-01
NGA-ADM2-72505758B57412385  5.3086e-01 -2.8619e-04  5.5148e-02  2.2618e+00
NGA-ADM2-72505758B57514033  8.0704e-02 -6.3301e-05  9.7476e-03  8.1806e-01
NGA-ADM2-72505758B57638513  1.1436e+00 -2.5402e-03  4.8838e-01  1.6401e+00
NGA-ADM2-72505758B57815144  4.5343e-01 -5.8659e-04  7.5136e-02  1.6564e+00
NGA-ADM2-72505758B57963290  4.5343e-01 -5.8659e-04  6.4318e-02  1.7902e+00
NGA-ADM2-72505758B58223447  4.8117e+00 -1.1828e-02  1.2824e+00  4.2595e+00
NGA-ADM2-72505758B5824220   4.5343e-01 -5.8659e-04  6.4318e-02  1.7902e+00
NGA-ADM2-72505758B58295941  4.5343e-01 -5.8659e-04  1.1300e-01  1.3506e+00
NGA-ADM2-72505758B5834354   8.1097e-03 -1.2418e-05  1.3623e-03  2.2005e-01
NGA-ADM2-72505758B58432429  4.9277e-01 -7.5299e-04  1.1587e-01  1.4498e+00
NGA-ADM2-72505758B58640661 -8.0003e-02 -2.8378e-03  3.1046e-01 -1.3849e-01
NGA-ADM2-72505758B5875612   4.5045e-01 -5.8659e-04  7.5136e-02  1.6455e+00
NGA-ADM2-72505758B59054861  1.6441e-01 -3.4150e-04  3.7453e-02  8.5131e-01
NGA-ADM2-72505758B59091347 -8.6499e-01 -2.4366e-04  4.6953e-02 -3.9907e+00
NGA-ADM2-72505758B59710243  4.5343e-01 -5.8659e-04  9.0281e-02  1.5110e+00
NGA-ADM2-72505758B5987673   4.5343e-01 -5.8659e-04  7.5136e-02  1.6564e+00
NGA-ADM2-72505758B59879704  4.3390e+00 -1.2248e-02  3.1132e+00  2.4661e+00
NGA-ADM2-72505758B60171436  2.1597e+00 -5.3818e-03  5.1319e-01  3.0222e+00
NGA-ADM2-72505758B60425686  4.5343e-01 -5.8659e-04  9.0281e-02  1.5110e+00
NGA-ADM2-72505758B60502549  4.5343e-01 -5.8659e-04  7.5136e-02  1.6564e+00
NGA-ADM2-72505758B60765301  1.5450e+00 -2.1057e-02  2.2616e+00  1.0414e+00
NGA-ADM2-72505758B61058152  5.0309e-02 -2.0075e-05  3.8694e-03  8.0909e-01
NGA-ADM2-72505758B61328021 -4.7732e-02 -3.0705e-04  3.9341e-02 -2.3910e-01
NGA-ADM2-72505758B6140913   2.4282e+00 -2.2592e-03  3.4712e-01  4.1253e+00
NGA-ADM2-72505758B614754    4.5343e-01 -5.8659e-04  9.0281e-02  1.5110e+00
NGA-ADM2-72505758B61554030  4.5045e-01 -5.8659e-04  7.5136e-02  1.6455e+00
NGA-ADM2-72505758B61584452  4.5343e-01 -5.8659e-04  7.5136e-02  1.6564e+00
NGA-ADM2-72505758B61679125  4.5343e-01 -5.8659e-04  7.5136e-02  1.6564e+00
NGA-ADM2-72505758B6178712   4.5343e-01 -5.8659e-04  9.0281e-02  1.5110e+00
NGA-ADM2-72505758B61803394  4.5343e-01 -5.8659e-04  7.5136e-02  1.6564e+00
NGA-ADM2-72505758B61833663  4.4448e-01 -5.8659e-04  2.2658e-01  9.3500e-01
NGA-ADM2-72505758B61849091  1.5612e-01 -5.8659e-04  4.4847e-02  7.3998e-01
NGA-ADM2-72505758B6187391   2.9540e-02 -1.8759e-04  2.8883e-02  1.7492e-01
NGA-ADM2-72505758B61968000 -1.6243e-01 -9.7408e-05  1.0686e-02 -1.5704e+00
NGA-ADM2-72505758B62110738  3.3301e+00 -1.3695e-03  2.6362e-01  6.4887e+00
NGA-ADM2-72505758B62204667  3.8627e-01 -5.8659e-04  1.1300e-01  1.1508e+00
NGA-ADM2-72505758B62431971  1.0249e-01 -2.5474e-04  3.9220e-02  5.1881e-01
NGA-ADM2-72505758B62522831  2.1074e+00 -2.5402e-03  2.7799e-01  4.0018e+00
NGA-ADM2-72505758B6253464   4.5343e-01 -5.8659e-04  7.5136e-02  1.6564e+00
NGA-ADM2-72505758B62747799  5.0483e+00 -5.2424e-03  8.0308e-01  5.6391e+00
NGA-ADM2-72505758B62799042  4.5144e-01 -5.8659e-04  4.9895e-02  2.0237e+00
NGA-ADM2-72505758B62812657  2.4149e+00 -4.1927e-03  4.0028e-01  3.8237e+00
NGA-ADM2-72505758B62943467  3.4708e-02 -1.3884e-04  1.7791e-02  2.6125e-01
NGA-ADM2-72505758B62956588  1.7014e-01 -2.0075e-05  2.5729e-03  3.3547e+00
NGA-ADM2-72505758B63001706  6.8508e-01 -1.2316e-03  1.3495e-01  1.8682e+00
NGA-ADM2-72505758B63074678  2.5317e-02 -2.7444e-04  5.2883e-02  1.1128e-01
NGA-ADM2-72505758B63382694 -4.5048e-03 -4.2752e-07  8.2404e-05 -4.9621e-01
NGA-ADM2-72505758B63641874  5.1210e-01 -2.8619e-04  2.7430e-02  3.0937e+00
NGA-ADM2-72505758B63662909  6.1049e-02 -2.7444e-04  7.0603e-02  2.3079e-01
NGA-ADM2-72505758B636923    1.0754e-01 -2.4366e-04  3.1221e-02  6.1003e-01
NGA-ADM2-72505758B63774666  4.5343e-01 -5.8659e-04  1.5086e-01  1.1689e+00
NGA-ADM2-72505758B63992612  4.5343e-01 -5.8659e-04  6.4318e-02  1.7902e+00
NGA-ADM2-72505758B64173383  1.3695e-01 -1.3884e-04  2.1378e-02  9.3759e-01
NGA-ADM2-72505758B64244244  4.5343e-01 -5.8659e-04  7.5136e-02  1.6564e+00
NGA-ADM2-72505758B64250128  4.5343e-01 -5.8659e-04  7.5136e-02  1.6564e+00
NGA-ADM2-72505758B64450018  3.1256e+00 -6.4092e-03  5.4199e-01  4.2543e+00
NGA-ADM2-72505758B64474046  3.7761e-02 -1.1721e-04  1.8048e-02  2.8196e-01
NGA-ADM2-72505758B64572421  4.5343e-01 -5.8659e-04  1.1300e-01  1.3506e+00
NGA-ADM2-72505758B64703850  1.0345e-01 -1.3884e-04  1.1815e-02  9.5301e-01
NGA-ADM2-72505758B64792691  3.1868e+00 -6.7193e-03  5.6802e-01  4.2373e+00
NGA-ADM2-72505758B6536467   3.8422e-01 -4.5726e-03  7.0095e-01  4.6438e-01
NGA-ADM2-72505758B65494204  4.5343e-01 -5.8659e-04  1.5086e-01  1.1689e+00
NGA-ADM2-72505758B65514383  7.7383e-02 -2.7444e-04  4.2252e-02  3.7780e-01
NGA-ADM2-72505758B65565348  1.5556e+00 -1.2997e-03  3.3401e-01  2.6939e+00
NGA-ADM2-72505758B65644548  7.8563e-01 -1.6674e-03  2.1335e-01  1.7045e+00
NGA-ADM2-72505758B65886725  2.5317e-01 -5.4117e-04  8.3293e-02  8.7910e-01
NGA-ADM2-72505758B65916530  4.5343e-01 -5.8659e-04  7.5136e-02  1.6564e+00
NGA-ADM2-72505758B66076488  4.5343e-01 -5.8659e-04  9.0281e-02  1.5110e+00
NGA-ADM2-72505758B66114245  8.7157e-02 -9.7408e-05  9.3379e-03  9.0295e-01
NGA-ADM2-72505758B6619157   4.5343e-01 -5.8659e-04  6.4318e-02  1.7902e+00
NGA-ADM2-72505758B66230476 -1.5289e-01 -3.1948e-04  2.0306e-02 -1.0706e+00
NGA-ADM2-72505758B66286397  4.5120e-01 -5.8659e-04  5.6205e-02  1.9056e+00
NGA-ADM2-72505758B66300646  4.5343e-01 -5.8659e-04  6.4318e-02  1.7902e+00
NGA-ADM2-72505758B66308875 -2.4064e-02 -4.9114e-06  1.8982e-03 -5.5222e-01
NGA-ADM2-72505758B66311687  1.7502e-02 -1.0067e-05  1.1045e-03  5.2695e-01
NGA-ADM2-72505758B66384798  1.2750e+00 -1.3330e-02  1.2609e+00  1.1473e+00
NGA-ADM2-72505758B6675111  -1.1980e-01 -5.1335e-04  6.5760e-02 -4.6516e-01
NGA-ADM2-72505758B67103889 -1.9496e-02 -2.5869e-05  4.9861e-03 -2.7574e-01
NGA-ADM2-72505758B67188591  4.7998e-01 -1.8273e-03  1.7487e-01  1.1522e+00
NGA-ADM2-72505758B67228552 -3.6522e-03 -2.5938e-06  4.9995e-04 -1.6323e-01
NGA-ADM2-72505758B67267634  2.5011e+00 -6.8770e-03  5.2246e-01  3.4697e+00
NGA-ADM2-72505758B67283121  2.0436e+00 -2.6376e-03  2.5221e-01  4.0745e+00
NGA-ADM2-72505758B6732783  -1.2585e-02 -2.5938e-06  4.9995e-04 -5.6272e-01
NGA-ADM2-72505758B67592189  4.5343e-01 -5.8659e-04  1.1300e-01  1.3506e+00
NGA-ADM2-72505758B67778003 -2.9551e-02 -7.9439e-05  1.2233e-02 -2.6647e-01
NGA-ADM2-72505758B6786568   4.5343e-01 -5.8659e-04  7.5136e-02  1.6564e+00
NGA-ADM2-72505758B67905963 -4.2520e-02 -1.2418e-05  3.1954e-03 -7.5197e-01
NGA-ADM2-72505758B68001848  1.3114e-01 -1.0446e-04  2.6878e-02  8.0051e-01
NGA-ADM2-72505758B68194313  4.5343e-01 -5.8659e-04  9.0281e-02  1.5110e+00
NGA-ADM2-72505758B68200680 -3.5530e-03 -2.5938e-06  3.3243e-04 -1.9473e-01
NGA-ADM2-72505758B68356378  4.5343e-01 -5.8659e-04  4.4847e-02  2.1439e+00
NGA-ADM2-72505758B68486014  7.3896e+00 -1.2461e-02  1.5771e+00  5.8941e+00
NGA-ADM2-72505758B68552788  2.9102e-01 -5.4117e-04  8.3293e-02  1.0102e+00
NGA-ADM2-72505758B68678547  7.4255e-02 -6.5165e-04  1.2552e-01  2.1143e-01
NGA-ADM2-72505758B6884405   4.5343e-01 -5.8659e-04  9.0281e-02  1.5110e+00
NGA-ADM2-72505758B68875813  4.9534e-01 -2.0810e-03  4.0027e-01  7.8623e-01
NGA-ADM2-72505758B68878432  4.5343e-01 -5.8659e-04  6.4318e-02  1.7902e+00
NGA-ADM2-72505758B68896460 -3.0259e-02 -5.4031e-05  1.0414e-02 -2.9598e-01
NGA-ADM2-72505758B69061814  3.2060e-03 -9.1702e-08  1.0061e-05  1.0108e+00
NGA-ADM2-72505758B69218817  1.5946e-01 -1.9733e-04  5.0768e-02  7.0858e-01
NGA-ADM2-72505758B69255840  6.8544e-02 -6.3301e-05  8.1125e-03  7.6172e-01
NGA-ADM2-72505758B69267419  4.5343e-01 -5.8659e-04  5.6205e-02  1.9151e+00
NGA-ADM2-72505758B69319692  4.5343e-01 -5.8659e-04  6.4318e-02  1.7902e+00
NGA-ADM2-72505758B69353048  4.5343e-01 -5.8659e-04  7.5136e-02  1.6564e+00
NGA-ADM2-72505758B69357183  1.0385e+00 -1.2316e-03  1.5765e-01  2.6187e+00
NGA-ADM2-72505758B69384871 -2.1920e-01 -6.3301e-05  6.9445e-03 -2.6296e+00
NGA-ADM2-72505758B69642516  1.2144e-01 -4.0882e-05  6.2955e-03  1.5311e+00
NGA-ADM2-72505758B69788799  4.5343e-01 -5.8659e-04  6.4318e-02  1.7902e+00
NGA-ADM2-72505758B70059085  8.4271e-01 -1.4413e-03  3.7035e-01  1.3871e+00
NGA-ADM2-72505758B70119517  2.1086e-01 -2.1471e-04  2.3551e-02  1.3754e+00
NGA-ADM2-72505758B70167647 -1.3802e-01 -1.5902e-03  1.1027e-01 -4.1084e-01
NGA-ADM2-72505758B70182243  1.8984e-01 -3.0705e-04  3.9341e-02  9.5865e-01
NGA-ADM2-72505758B70270736  4.5343e-01 -5.8659e-04  1.5086e-01  1.1689e+00
NGA-ADM2-72505758B70271338  1.4230e+00 -1.5902e-03  1.7419e-01  3.4134e+00
NGA-ADM2-72505758B70495723 -2.6749e-02 -2.7444e-04  5.2883e-02 -1.1513e-01
NGA-ADM2-72505758B70869724  4.5343e-01 -5.8659e-04  6.4318e-02  1.7902e+00
NGA-ADM2-72505758B70905299  4.5343e-01 -5.8659e-04  6.4318e-02  1.7902e+00
NGA-ADM2-72505758B70998471  4.5343e-01 -5.8659e-04  1.5086e-01  1.1689e+00
NGA-ADM2-72505758B71477681  5.1971e-02 -1.6230e-04  2.4989e-02  3.2979e-01
NGA-ADM2-72505758B718280    9.2798e+00 -1.4688e-02  1.5878e+00  7.3761e+00
NGA-ADM2-72505758B7184000   4.5343e-01 -5.8659e-04  1.5086e-01  1.1689e+00
NGA-ADM2-72505758B71906601  4.5343e-01 -5.8659e-04  1.5086e-01  1.1689e+00
NGA-ADM2-72505758B71918331  2.7246e-01 -4.1587e-04  8.0125e-02  9.6400e-01
NGA-ADM2-72505758B71990951  4.5343e-01 -5.8659e-04  7.5136e-02  1.6564e+00
NGA-ADM2-72505758B72019004  6.2395e-03 -4.8993e-05  4.1696e-03  9.7388e-02
NGA-ADM2-72505758B72123387  1.5576e+00 -7.1980e-03  7.8402e-01  1.7673e+00
NGA-ADM2-72505758B7217003   4.5343e-01 -5.8659e-04  1.5086e-01  1.1689e+00
NGA-ADM2-72505758B72331537  4.5343e-01 -5.8659e-04  9.0281e-02  1.5110e+00
NGA-ADM2-72505758B72340078  2.8840e-01 -4.9757e-04  6.3739e-02  1.1443e+00
NGA-ADM2-72505758B72369186  1.0236e+00 -2.2512e-04  2.4693e-02  6.5155e+00
NGA-ADM2-72505758B72408011  4.4896e-01 -5.8659e-04  1.1300e-01  1.3373e+00
NGA-ADM2-72505758B72527598  2.4059e-01 -4.3031e-04  4.1238e-02  1.1869e+00
NGA-ADM2-72505758B72583543  3.9362e-02 -1.1721e-04  1.8048e-02  2.9387e-01
NGA-ADM2-72505758B72901624  1.9551e-01 -3.7777e-04  4.1430e-02  9.6238e-01
NGA-ADM2-72505758B72996990  4.5343e-01 -5.8659e-04  9.0281e-02  1.5110e+00
NGA-ADM2-72505758B73155659  1.8254e-01 -5.8659e-04  5.6205e-02  7.7242e-01
NGA-ADM2-72505758B73169585 -8.6779e-02 -2.7444e-04  4.2252e-02 -4.2084e-01
NGA-ADM2-72505758B7318634   2.5638e+00 -2.9406e-03  5.6513e-01  3.4144e+00
NGA-ADM2-72505758B7324564   3.0134e+00 -1.1212e-02  1.7073e+00  2.3148e+00
NGA-ADM2-72505758B73267274  9.2212e-02 -2.9563e-05  5.6981e-03  1.2220e+00
NGA-ADM2-72505758B73302858  4.5343e-01 -5.8659e-04  9.0281e-02  1.5110e+00
NGA-ADM2-72505758B73332929  7.4811e-01 -1.2316e-03  1.3495e-01  2.0398e+00
NGA-ADM2-72505758B73850861  8.9904e-01 -5.5762e-04  8.5825e-02  3.0707e+00
NGA-ADM2-72505758B74167895  4.5343e-01 -5.8659e-04  7.5136e-02  1.6564e+00
NGA-ADM2-72505758B74224076  3.1394e-01 -2.8378e-03  3.1046e-01  5.6853e-01
NGA-ADM2-72505758B74273353  3.3260e-01 -4.5581e-04  8.7816e-02  1.1239e+00
NGA-ADM2-72505758B74442045  6.7420e+00 -1.0811e-02  1.6468e+00  5.2621e+00
NGA-ADM2-72505758B74527534  2.4206e-02 -1.0067e-05  1.5503e-03  6.1504e-01
NGA-ADM2-72505758B74576641  1.5065e-01 -1.1721e-04  1.5020e-02  1.2302e+00
NGA-ADM2-72505758B74718112  4.5343e-01 -5.8659e-04  7.5136e-02  1.6564e+00
NGA-ADM2-72505758B7490938   6.7204e-02 -4.8993e-05  1.2607e-02  5.9897e-01
NGA-ADM2-72505758B75034141  5.7376e+00 -5.9579e-03  7.5905e-01  6.5924e+00
NGA-ADM2-72505758B75040986 -2.1624e-01 -1.9733e-04  7.6251e-02 -7.8239e-01
NGA-ADM2-72505758B75230852  1.1230e+00 -5.1048e-03  5.5720e-01  1.5113e+00
NGA-ADM2-72505758B7553151   2.3322e+00 -2.7368e-03  4.2030e-01  3.6015e+00
NGA-ADM2-72505758B75536077  7.4198e-02 -6.5905e-06  1.0149e-03  2.3293e+00
NGA-ADM2-72505758B75784992  4.5343e-01 -5.8659e-04  9.0281e-02  1.5110e+00
NGA-ADM2-72505758B75801679  4.5343e-01 -5.8659e-04  9.0281e-02  1.5110e+00
NGA-ADM2-72505758B75908239  4.5343e-01 -5.8659e-04  6.4318e-02  1.7902e+00
NGA-ADM2-72505758B75983929 -1.0206e-02 -1.2418e-05  1.9123e-03 -2.3311e-01
NGA-ADM2-72505758B76052259  3.2115e-02 -1.7053e-05  2.6261e-03  6.2704e-01
NGA-ADM2-72505758B76392163 -1.1298e-01 -4.8993e-05  5.3749e-03 -1.5403e+00
NGA-ADM2-72505758B76566778 -1.5789e-02 -6.5905e-06  8.4466e-04 -5.4303e-01
NGA-ADM2-72505758B7691229   2.3855e-02 -2.4366e-04  4.6953e-02  1.1121e-01
NGA-ADM2-72505758B77062793  4.4746e-01 -5.8659e-04  1.5086e-01  1.1536e+00
NGA-ADM2-72505758B7732292   8.1107e-02 -3.6516e-05  4.6799e-03  1.1861e+00
NGA-ADM2-72505758B77767589 -6.9215e-02 -1.7136e-04  2.1959e-02 -4.6593e-01
NGA-ADM2-72505758B77907079  5.2450e-01 -9.7765e-04  1.5041e-01  1.3549e+00
NGA-ADM2-72505758B78258316 -3.8245e-03 -2.5869e-05  3.3154e-03 -6.5971e-02
NGA-ADM2-72505758B783054    2.4591e+00 -3.4823e-03  8.9298e-01  2.6059e+00
NGA-ADM2-72505758B78395267  7.9393e-02 -1.1721e-04  1.8048e-02  5.9185e-01
NGA-ADM2-72505758B7845389   3.1015e-01 -5.8659e-04  5.6205e-02  1.3107e+00
NGA-ADM2-72505758B78492046  1.8697e-01 -1.8759e-04  2.0577e-02  1.3047e+00
NGA-ADM2-72505758B78527113  4.5088e-01 -5.8659e-04  6.4318e-02  1.7801e+00
NGA-ADM2-72505758B78527729  4.5088e-01 -5.8659e-04  6.4318e-02  1.7801e+00
NGA-ADM2-72505758B78555816  4.1569e-02 -4.8993e-05  5.3749e-03  5.6767e-01
NGA-ADM2-72505758B7855953   4.0112e-01 -5.4117e-04  4.1376e-02  1.9746e+00
NGA-ADM2-72505758B78597532  8.3800e-01 -2.5402e-03  3.9020e-01  1.3456e+00
NGA-ADM2-72505758B78619683 -6.6675e-02 -1.2493e-04  1.1976e-02 -6.0813e-01
NGA-ADM2-72505758B78698197 -2.5281e-02 -1.6230e-04  1.2560e-01 -7.0877e-02
NGA-ADM2-72505758B78741094  4.5343e-01 -5.8659e-04  9.0281e-02  1.5110e+00
NGA-ADM2-72505758B79155077  4.5343e-01 -5.8659e-04  7.5136e-02  1.6564e+00
NGA-ADM2-72505758B79178637  7.3751e-01 -5.1335e-04  1.3203e-01  2.0311e+00
NGA-ADM2-72505758B79193959  4.5343e-01 -5.8659e-04  6.4318e-02  1.7902e+00
NGA-ADM2-72505758B79316383  5.4055e-01 -1.0384e-03  4.0092e-01  8.5534e-01
NGA-ADM2-72505758B79444654  3.7716e+00 -2.3510e-03  4.5209e-01  5.6128e+00
NGA-ADM2-72505758B79493017  3.5295e-01 -5.4117e-04  8.3293e-02  1.2248e+00
NGA-ADM2-72505758B7968540   5.0995e-01 -8.0641e-04  1.2409e-01  1.4500e+00
NGA-ADM2-72505758B79803896  4.5343e-01 -5.8659e-04  1.5086e-01  1.1689e+00
NGA-ADM2-72505758B79815894  7.2133e-02 -3.0705e-04  5.9166e-02  2.9781e-01
NGA-ADM2-72505758B79902123  4.5343e-01 -5.8659e-04  1.1300e-01  1.3506e+00
NGA-ADM2-72505758B79945925  2.3103e-03 -9.7408e-05  1.8773e-02  1.7572e-02
NGA-ADM2-72505758B79983056  2.6950e-02 -3.6516e-05  4.0061e-03  4.2637e-01
NGA-ADM2-72505758B80057854  4.0180e-01 -3.1948e-04  3.5039e-02  2.1482e+00
NGA-ADM2-72505758B80290097  2.0710e-01 -1.6230e-04  4.1757e-02  1.0143e+00
NGA-ADM2-72505758B8045942   4.5343e-01 -5.8659e-04  7.5136e-02  1.6564e+00
NGA-ADM2-72505758B80517430  4.5343e-01 -5.8659e-04  5.6205e-02  1.9151e+00
NGA-ADM2-72505758B80733792  2.3253e-01 -5.4117e-04  8.3293e-02  8.0757e-01
NGA-ADM2-72505758B80737371 -2.8470e-03 -4.2752e-07  4.6904e-05 -4.1564e-01
NGA-ADM2-72505758B80966644  4.5343e-01 -5.8659e-04  7.5136e-02  1.6564e+00
NGA-ADM2-72505758B81144344  1.7925e-01 -3.4150e-04  5.2572e-02  7.8326e-01
NGA-ADM2-72505758B8143254   2.0954e+00 -1.5156e-02  1.9130e+00  1.5260e+00
NGA-ADM2-72505758B8152058   3.2027e-02 -1.0067e-05  2.5905e-03  6.2945e-01
NGA-ADM2-72505758B81562716  2.5904e+00 -6.1065e-03  6.6587e-01  3.1820e+00
NGA-ADM2-72505758B81594808  2.0476e-01 -3.4150e-04  8.7848e-02  6.9199e-01
NGA-ADM2-72505758B81600634  4.5343e-01 -5.8659e-04  6.4318e-02  1.7902e+00
NGA-ADM2-72505758B81840583 -2.6164e-03 -9.1702e-08  2.3598e-05 -5.3858e-01
NGA-ADM2-72505758B8232613   2.2649e-02 -5.4117e-04  4.6033e-02  1.0808e-01
NGA-ADM2-72505758B82571199  4.5343e-01 -5.8659e-04  6.4318e-02  1.7902e+00
NGA-ADM2-72505758B82611067  1.9248e-03 -1.5863e-06  1.5209e-04  1.5621e-01
NGA-ADM2-72505758B82612540  6.2159e-02 -9.7408e-05  1.4999e-02  5.0833e-01
NGA-ADM2-72505758B82650021  4.5343e-01 -5.8659e-04  1.1300e-01  1.3506e+00
NGA-ADM2-72505758B82952463  1.5341e-01 -4.5581e-04  7.0161e-02  5.8088e-01
NGA-ADM2-72505758B82980400 -6.8442e-01 -4.5581e-04  1.1724e-01 -1.9975e+00
NGA-ADM2-72505758B83115922  1.6424e+00 -1.1010e-03  2.1197e-01  3.5696e+00
NGA-ADM2-72505758B83213265  7.1258e-02 -2.7444e-04  3.5164e-02  3.8146e-01
NGA-ADM2-72505758B83356374  4.5343e-01 -5.8659e-04  7.5136e-02  1.6564e+00
NGA-ADM2-72505758B83595220  4.5343e-01 -5.8659e-04  1.5086e-01  1.1689e+00
NGA-ADM2-72505758B83712041  4.5343e-01 -5.8659e-04  7.5136e-02  1.6564e+00
NGA-ADM2-72505758B83816053  1.2776e-02 -1.5863e-06  2.4429e-04  8.1749e-01
NGA-ADM2-72505758B83963728  3.3919e-01 -5.4117e-04  4.1376e-02  1.6702e+00
NGA-ADM2-72505758B83971794  4.0663e+00 -3.7118e-03  4.0571e-01  6.3898e+00
NGA-ADM2-72505758B84114048  2.7804e-02 -1.8759e-04  2.0577e-02  1.9514e-01
NGA-ADM2-72505758B84194123  4.5343e-01 -5.8659e-04  1.1300e-01  1.3506e+00
NGA-ADM2-72505758B84339715  7.6317e-01 -1.4413e-03  5.5625e-01  1.0252e+00
NGA-ADM2-72505758B84457876  2.7866e-01 -4.5581e-04  1.1724e-01  8.1517e-01
NGA-ADM2-72505758B84478450  2.4120e-01 -3.4150e-04  4.3753e-02  1.1548e+00
NGA-ADM2-72505758B84831958  1.9848e-01 -3.0705e-04  5.9166e-02  8.1723e-01
NGA-ADM2-72505758B84865629  2.2364e+00 -2.6376e-03  4.0511e-01  3.5177e+00
NGA-ADM2-72505758B85138406  4.5343e-01 -5.8659e-04  1.1300e-01  1.3506e+00
NGA-ADM2-72505758B85275479  3.8803e-02 -9.7408e-05  2.5064e-02  2.4572e-01
NGA-ADM2-72505758B85519087  4.5343e-01 -5.8659e-04  9.0281e-02  1.5110e+00
NGA-ADM2-72505758B86064137  4.5343e-01 -5.8659e-04  6.4318e-02  1.7902e+00
NGA-ADM2-72505758B86185926  4.1187e-01 -5.4117e-04  5.1855e-02  1.8111e+00
NGA-ADM2-72505758B8622199   3.5371e+00 -1.2675e-02  1.9272e+00  2.5570e+00
NGA-ADM2-72505758B86358915 -7.5909e-02 -7.9439e-05  1.0181e-02 -7.5154e-01
NGA-ADM2-72505758B8652160   3.8231e-01 -6.0372e-04  3.2795e-02  2.1145e+00
NGA-ADM2-72505758B86583227  1.1175e+00 -1.5148e-03  1.6594e-01  2.7470e+00
NGA-ADM2-72505758B86734523  4.5343e-01 -5.8659e-04  4.9895e-02  2.0326e+00
NGA-ADM2-72505758B86763634  4.5343e-01 -5.8659e-04  9.0281e-02  1.5110e+00
NGA-ADM2-72505758B86773608  3.4935e-02 -4.1587e-04  1.0697e-01  1.0808e-01
NGA-ADM2-72505758B86821483  1.3309e-01 -5.4031e-05  8.3202e-03  1.4596e+00
NGA-ADM2-72505758B8687564   4.5343e-01 -5.8659e-04  7.5136e-02  1.6564e+00
NGA-ADM2-72505758B86879364  4.5343e-01 -5.8659e-04  5.6205e-02  1.9151e+00
NGA-ADM2-72505758B8726241   1.6848e+00 -5.9579e-03  7.5905e-01  1.9407e+00
NGA-ADM2-72505758B8775504   2.7822e+00 -1.9101e-03  2.9358e-01  5.1383e+00
NGA-ADM2-72505758B87811615  1.0432e+01 -7.5745e-02  7.6807e+00  3.7914e+00
NGA-ADM2-72505758B87995813  4.5343e-01 -5.8659e-04  1.1300e-01  1.3506e+00
NGA-ADM2-72505758B88150775  5.0802e+00 -2.9406e-03  2.2694e+00  3.3743e+00
NGA-ADM2-72505758B88452088 -1.6248e-01 -4.9757e-04  6.3739e-02 -6.4162e-01
NGA-ADM2-72505758B88587475  4.5343e-01 -5.8659e-04  9.0281e-02  1.5110e+00
NGA-ADM2-72505758B88727897  1.4275e+00 -3.7118e-03  5.6948e-01  1.8965e+00
NGA-ADM2-72505758B88761962 -2.9279e-02 -3.7118e-03  4.7395e-01 -3.7138e-02
NGA-ADM2-72505758B88921590  4.5343e-01 -5.8659e-04  7.5136e-02  1.6564e+00
NGA-ADM2-72505758B88925335  4.5343e-01 -5.8659e-04  1.1300e-01  1.3506e+00
NGA-ADM2-72505758B8918259  -1.9299e-01 -4.8993e-05  7.5445e-03 -2.2213e+00
NGA-ADM2-72505758B89235976  6.5654e-02 -3.0705e-04  5.9166e-02  2.7118e-01
NGA-ADM2-72505758B89515171  3.0176e+00 -3.1518e-03  3.4470e-01  5.1451e+00
NGA-ADM2-72505758B8960534   8.0285e-02 -1.2418e-05  1.1905e-03  2.3272e+00
NGA-ADM2-72505758B89722002  2.6416e-01 -4.1587e-04  6.4017e-02  1.0457e+00
NGA-ADM2-72505758B89731144  8.3886e-01 -4.3031e-04  6.6239e-02  3.2611e+00
NGA-ADM2-72505758B89894474  3.2785e-02 -2.5869e-05  3.9837e-03  5.1985e-01
NGA-ADM2-72505758B90027140  4.5343e-01 -5.8659e-04  7.5136e-02  1.6564e+00
NGA-ADM2-72505758B90250628  6.8488e-01 -7.0140e-04  7.6898e-02  2.4723e+00
NGA-ADM2-72505758B90811761  3.9433e-01 -4.7092e-04  4.0060e-02  1.9725e+00
NGA-ADM2-72505758B91050715  1.9663e-02 -7.9439e-05  1.0181e-02  1.9566e-01
NGA-ADM2-72505758B91135250  2.4327e+00 -2.0810e-03  2.2783e-01  5.1009e+00
NGA-ADM2-72505758B913149   -5.4288e-02 -2.5869e-05  2.4801e-03 -1.0896e+00
NGA-ADM2-72505758B91510140  2.9931e+00 -1.8273e-03  2.3377e-01  6.1943e+00
NGA-ADM2-72505758B91579398 -1.5929e-01 -2.5869e-05  3.3154e-03 -2.7660e+00
NGA-ADM2-72505758B91650930  7.9393e-01 -2.8619e-04  2.4351e-02  5.0896e+00
NGA-ADM2-72505758B91687942  4.5343e-01 -5.8659e-04  7.5136e-02  1.6564e+00
NGA-ADM2-72505758B92105435  1.3488e-01 -1.6230e-04  2.4989e-02  8.5424e-01
NGA-ADM2-72505758B92139849  3.8462e-01 -4.9757e-04  1.2798e-01  1.0765e+00
NGA-ADM2-72505758B92277191 -2.7939e-02 -6.5905e-06  1.0149e-03 -8.7678e-01
NGA-ADM2-72505758B92576019  2.2448e-01 -1.4723e-04  1.8867e-02  1.6353e+00
NGA-ADM2-72505758B92786354 -3.7451e-02 -1.4723e-04  1.6151e-02 -2.9353e-01
NGA-ADM2-72505758B92819273  4.5343e-01 -5.8659e-04  7.5136e-02  1.6564e+00
NGA-ADM2-72505758B92921679 -6.1460e-02 -2.7444e-04  3.5164e-02 -3.2629e-01
NGA-ADM2-72505758B92954057  6.5097e-02 -4.1587e-04  6.4017e-02  2.5893e-01
NGA-ADM2-72505758B93424331  4.5343e-01 -5.8659e-04  7.5136e-02  1.6564e+00
NGA-ADM2-72505758B93427284  3.0203e-01 -3.1948e-04  4.0933e-02  1.4944e+00
NGA-ADM2-72505758B93593012 -5.1224e-01 -9.7408e-05  1.8773e-02 -3.7378e+00
NGA-ADM2-72505758B93638472  3.1940e-01 -5.4117e-04  1.0425e-01  9.9090e-01
NGA-ADM2-72505758B93649439  4.4985e-01 -5.8659e-04  9.0281e-02  1.4991e+00
NGA-ADM2-72505758B93709657  4.5343e-01 -5.8659e-04  7.5136e-02  1.6564e+00
NGA-ADM2-72505758B93737389  1.0354e-02 -1.5863e-06  2.4429e-04  6.6255e-01
NGA-ADM2-72505758B93761587  4.5343e-01 -5.8659e-04  6.4318e-02  1.7902e+00
NGA-ADM2-72505758B93767969  4.5343e-01 -5.8659e-04  5.6205e-02  1.9151e+00
NGA-ADM2-72505758B94189690  9.4534e-02 -2.7444e-04  4.2252e-02  4.6124e-01
NGA-ADM2-72505758B94509825  4.5343e-01 -5.8659e-04  9.0281e-02  1.5110e+00
NGA-ADM2-72505758B94606913  2.0110e+00 -1.2997e-03  2.5018e-01  4.0232e+00
NGA-ADM2-72505758B94629448  4.5343e-01 -5.8659e-04  9.0281e-02  1.5110e+00
NGA-ADM2-72505758B94685339  4.5343e-01 -5.8659e-04  1.1300e-01  1.3506e+00
NGA-ADM2-72505758B94886311  2.8505e+00 -1.9946e-03  1.9085e-01  6.5296e+00
NGA-ADM2-72505758B94925970  3.2078e+00 -1.9946e-03  1.6942e-01  7.7984e+00
NGA-ADM2-72505758B94954595  4.5343e-01 -5.8659e-04  5.6205e-02  1.9151e+00
NGA-ADM2-72505758B95154533  1.2890e+00 -1.2997e-03  1.6635e-01  3.1636e+00
NGA-ADM2-72505758B95191090  4.5343e-01 -5.8659e-04  1.1300e-01  1.3506e+00
NGA-ADM2-72505758B95323810  4.5343e-01 -5.8659e-04  9.0281e-02  1.5110e+00
NGA-ADM2-72505758B95411855  2.3769e-01 -5.4117e-04  5.1855e-02  1.0462e+00
NGA-ADM2-72505758B95429572  6.4574e-02 -3.0705e-04  3.9341e-02  3.2711e-01
NGA-ADM2-72505758B95534398  1.8044e-01 -6.5165e-04  6.2434e-02  7.2475e-01
NGA-ADM2-72505758B95566521  6.8325e-03 -2.5869e-05  3.3154e-03  1.1911e-01
NGA-ADM2-72505758B95606818  2.8015e-02 -4.9114e-06  4.1800e-04  1.3705e+00
NGA-ADM2-72505758B95781523  4.5343e-01 -5.8659e-04  6.4318e-02  1.7902e+00
NGA-ADM2-72505758B9585780   1.0670e+00 -3.7118e-03  4.0571e-01  1.6810e+00
NGA-ADM2-72505758B95859729  3.8315e-01 -4.9690e-03  1.2723e+00  3.4409e-01
NGA-ADM2-72505758B95872281 -1.7815e-01 -2.4366e-04  4.6953e-02 -8.2105e-01
NGA-ADM2-72505758B95999274  4.5343e-01 -5.8659e-04  9.0281e-02  1.5110e+00
NGA-ADM2-72505758B9609327   4.5343e-01 -5.8659e-04  9.0281e-02  1.5110e+00
NGA-ADM2-72505758B9615674   2.0317e-01 -4.9757e-04  4.7680e-02  9.3273e-01
NGA-ADM2-72505758B96206882  2.0661e+00 -2.5402e-03  4.8838e-01  2.9601e+00
NGA-ADM2-72505758B96230569  1.6304e-02 -4.8993e-05  6.2789e-03  2.0638e-01
NGA-ADM2-72505758B9625976   2.1125e+00 -3.1518e-03  4.8384e-01  3.0416e+00
NGA-ADM2-72505758B96315687  6.1722e-02 -3.4150e-04  5.2572e-02  2.7068e-01
NGA-ADM2-72505758B96375167  2.6565e-02 -5.8659e-04  7.5136e-02  9.9054e-02
NGA-ADM2-72505758B96655345  4.5343e-01 -5.8659e-04  9.0281e-02  1.5110e+00
NGA-ADM2-72505758B9668183   1.8003e-02 -2.0075e-05  1.9246e-03  4.1083e-01
NGA-ADM2-72505758B96685701  4.5343e-01 -5.8659e-04  6.4318e-02  1.7902e+00
NGA-ADM2-72505758B96746323 -3.0735e-02 -5.3818e-03  1.0318e+00 -2.4960e-02
NGA-ADM2-72505758B9692286   4.5343e-01 -5.8659e-04  1.1300e-01  1.3506e+00
NGA-ADM2-72505758B96981662  4.5343e-01 -5.8659e-04  1.1300e-01  1.3506e+00
NGA-ADM2-72505758B97139317  4.5343e-01 -5.8659e-04  1.1300e-01  1.3506e+00
NGA-ADM2-72505758B97184317  2.6031e-02 -9.7408e-05  9.3379e-03  2.7039e-01
NGA-ADM2-72505758B9725515   4.5343e-01 -5.8659e-04  1.5086e-01  1.1689e+00
NGA-ADM2-72505758B97294598  1.6467e-01 -4.0882e-05  4.4850e-03  2.4595e+00
NGA-ADM2-72505758B97405906  8.4213e-03 -3.0705e-04  3.9341e-02  4.4005e-02
NGA-ADM2-72505758B97448934  4.5343e-01 -5.8659e-04  1.1300e-01  1.3506e+00
NGA-ADM2-72505758B9755199   3.3742e-02 -2.0075e-05  3.8694e-03  5.4276e-01
NGA-ADM2-72505758B98057596 -9.5767e-02 -2.5869e-05  2.2016e-03 -2.0404e+00
NGA-ADM2-72505758B98072407 -6.4016e-02 -1.0067e-05  1.5503e-03 -1.6256e+00
NGA-ADM2-72505758B98086722  1.3948e-01 -2.1471e-04  1.8270e-02  1.0335e+00
NGA-ADM2-72505758B98116860 -2.3258e-02 -2.5869e-05  2.4801e-03 -4.6650e-01
NGA-ADM2-72505758B98120163  4.5343e-01 -5.8659e-04  1.1300e-01  1.3506e+00
NGA-ADM2-72505758B98218468  4.5343e-01 -5.8659e-04  7.5136e-02  1.6564e+00
NGA-ADM2-72505758B98262124  1.9079e-01 -8.5820e-05  1.0998e-02  1.8201e+00
NGA-ADM2-72505758B98593855  4.5140e-01 -2.2512e-04  2.1578e-02  3.0745e+00
NGA-ADM2-72505758B98658548  2.2782e-02 -6.3301e-05  5.3871e-03  3.1126e-01
NGA-ADM2-72505758B98737176  4.5343e-01 -5.8659e-04  1.1300e-01  1.3506e+00
NGA-ADM2-72505758B98765613 -9.7229e-02 -2.5869e-05  3.3154e-03 -1.6882e+00
NGA-ADM2-72505758B99221548  1.0190e-01 -2.2512e-04  2.8846e-02  6.0127e-01
NGA-ADM2-72505758B99270352 -3.4152e-02 -1.7053e-05  1.6349e-03 -8.4423e-01
NGA-ADM2-72505758B99641746  4.4985e-01 -5.8659e-04  9.0281e-02  1.4991e+00
NGA-ADM2-72505758B99650649  3.0292e+00 -1.7465e-03  2.2344e-01  6.4119e+00
NGA-ADM2-72505758B99764805  4.5343e-01 -5.8659e-04  9.0281e-02  1.5110e+00
NGA-ADM2-72505758B9986554   6.7927e-02 -1.7136e-04  4.4090e-02  3.2431e-01
NGA-ADM2-72505758B99970923 -3.0153e-02 -2.5869e-05  6.6568e-03 -3.6926e-01
                           Pr.z....E.Ii..
NGA-ADM2-72505758B10049836         0.3402
NGA-ADM2-72505758B10063467         0.3199
NGA-ADM2-72505758B10065661         0.7195
NGA-ADM2-72505758B10302610         0.2480
NGA-ADM2-72505758B10682130         0.1308
NGA-ADM2-72505758B11317593         0.9770
NGA-ADM2-72505758B1132196          0.4531
NGA-ADM2-72505758B11373444         0.1811
NGA-ADM2-72505758B11735424         0.0734
NGA-ADM2-72505758B11870040         0.1308
NGA-ADM2-72505758B11997780         0.0555
NGA-ADM2-72505758B122892           0.1051
NGA-ADM2-72505758B12413588         0.0977
NGA-ADM2-72505758B1244901          0.4406
NGA-ADM2-72505758B12596325         0.0734
NGA-ADM2-72505758B12674914         0.0173
NGA-ADM2-72505758B12680831         0.1308
NGA-ADM2-72505758B12769973         0.0977
NGA-ADM2-72505758B12816297         0.2314
NGA-ADM2-72505758B13021078         0.0734
NGA-ADM2-72505758B13075745         0.0320
NGA-ADM2-72505758B13233811         0.5795
NGA-ADM2-72505758B13380599         0.6711
NGA-ADM2-72505758B13427126         0.2690
NGA-ADM2-72505758B13487741         0.0977
NGA-ADM2-72505758B13685756         0.2558
NGA-ADM2-72505758B139854           0.1768
NGA-ADM2-72505758B14016122         0.0734
NGA-ADM2-72505758B14174427         0.3556
NGA-ADM2-72505758B14213332         0.4447
NGA-ADM2-72505758B14369579         0.8831
NGA-ADM2-72505758B14654508         0.7129
NGA-ADM2-72505758B14842261         0.1558
NGA-ADM2-72505758B15135669         0.0555
NGA-ADM2-72505758B15152925         0.0003
NGA-ADM2-72505758B15168871         0.0762
NGA-ADM2-72505758B15269567         0.0873
NGA-ADM2-72505758B15283345         0.4341
NGA-ADM2-72505758B15329511         0.5952
NGA-ADM2-72505758B15626765         0.1370
NGA-ADM2-72505758B15745475         0.2246
NGA-ADM2-72505758B15928088         0.0000
NGA-ADM2-72505758B1616690          0.0000
NGA-ADM2-72505758B16281923         0.3755
NGA-ADM2-72505758B16283774         0.1768
NGA-ADM2-72505758B16331092         0.6638
NGA-ADM2-72505758B16408752         0.1386
NGA-ADM2-72505758B16424915         0.0046
NGA-ADM2-72505758B16610760         0.0734
NGA-ADM2-72505758B16696559         0.0979
NGA-ADM2-72505758B16765159         0.2295
NGA-ADM2-72505758B16773759         0.1308
NGA-ADM2-72505758B17259178         0.0005
NGA-ADM2-72505758B17453237         0.8444
NGA-ADM2-72505758B17534332         0.1308
NGA-ADM2-72505758B17563771         0.1768
NGA-ADM2-72505758B17614134         0.0160
NGA-ADM2-72505758B17633838         0.9903
NGA-ADM2-72505758B17736122         0.2353
NGA-ADM2-72505758B1782277          0.6005
NGA-ADM2-72505758B18027142         0.1811
NGA-ADM2-72505758B18156007         0.1308
NGA-ADM2-72505758B18272004         0.4790
NGA-ADM2-72505758B1827434          0.7987
NGA-ADM2-72505758B18295427         0.0587
NGA-ADM2-72505758B18326272         0.0003
NGA-ADM2-72505758B18376242         0.0285
NGA-ADM2-72505758B18447698         0.3077
NGA-ADM2-72505758B18534598         0.2375
NGA-ADM2-72505758B18548676         0.3872
NGA-ADM2-72505758B18747813         0.0014
NGA-ADM2-72505758B18888506         0.1308
NGA-ADM2-72505758B18960886         0.5366
NGA-ADM2-72505758B19119765         0.0835
NGA-ADM2-72505758B19327087         0.1308
NGA-ADM2-72505758B19376786         0.4591
NGA-ADM2-72505758B19458752         0.0820
NGA-ADM2-72505758B19462210         0.9581
NGA-ADM2-72505758B19539344         0.6256
NGA-ADM2-72505758B196939           0.0508
NGA-ADM2-72505758B19914513         0.2424
NGA-ADM2-72505758B20050296         0.0751
NGA-ADM2-72505758B20351569         0.0977
NGA-ADM2-72505758B20421162         0.6025
NGA-ADM2-72505758B20535362         0.5639
NGA-ADM2-72505758B20542872         0.4138
NGA-ADM2-72505758B20606047         0.6156
NGA-ADM2-72505758B20675427         0.2438
NGA-ADM2-72505758B20849864         0.9374
NGA-ADM2-72505758B21150125         0.0977
NGA-ADM2-72505758B21444598         0.0555
NGA-ADM2-72505758B21552075         0.0000
NGA-ADM2-72505758B2169568          0.6384
NGA-ADM2-72505758B2190517          0.8693
NGA-ADM2-72505758B21920023         0.0421
NGA-ADM2-72505758B2204672          0.0000
NGA-ADM2-72505758B22226897         0.0977
NGA-ADM2-72505758B22346210         0.2811
NGA-ADM2-72505758B22432067         0.3861
NGA-ADM2-72505758B22509400         0.9965
NGA-ADM2-72505758B22625464         0.0554
NGA-ADM2-72505758B22711214         0.1308
NGA-ADM2-72505758B22775279         0.5727
NGA-ADM2-72505758B22890603         0.0247
NGA-ADM2-72505758B22914768         0.4765
NGA-ADM2-72505758B22969834         0.9436
NGA-ADM2-72505758B23063504         0.0977
NGA-ADM2-72505758B23284206         0.4229
NGA-ADM2-72505758B23339862         0.0555
NGA-ADM2-72505758B23406569         0.6363
NGA-ADM2-72505758B23525102         0.1308
NGA-ADM2-72505758B23727233         0.0977
NGA-ADM2-72505758B23758727         0.9753
NGA-ADM2-72505758B23938972         0.6780
NGA-ADM2-72505758B24068194         0.8470
NGA-ADM2-72505758B24079849         0.4060
NGA-ADM2-72505758B24173949         0.5062
NGA-ADM2-72505758B24287701         0.1945
NGA-ADM2-72505758B24946110         0.1828
NGA-ADM2-72505758B24975398         0.0037
NGA-ADM2-72505758B25108439         0.1135
NGA-ADM2-72505758B25110832         0.5635
NGA-ADM2-72505758B25204428         0.1354
NGA-ADM2-72505758B25323941         0.4545
NGA-ADM2-72505758B25363477         0.0037
NGA-ADM2-72505758B25708171            NaN
NGA-ADM2-72505758B26082732         0.9414
NGA-ADM2-72505758B26198977         0.6322
NGA-ADM2-72505758B26243068         0.2424
NGA-ADM2-72505758B2628120          0.1768
NGA-ADM2-72505758B26346364         0.0555
NGA-ADM2-72505758B26429015         0.3433
NGA-ADM2-72505758B26523677         0.1768
NGA-ADM2-72505758B26556107         0.8975
NGA-ADM2-72505758B2657339          0.0734
NGA-ADM2-72505758B26581542         0.0000
NGA-ADM2-72505758B27276798         0.0977
NGA-ADM2-72505758B27408614         0.0000
NGA-ADM2-72505758B2745087          0.9158
NGA-ADM2-72505758B27539273         0.0977
NGA-ADM2-72505758B27542400         0.2474
NGA-ADM2-72505758B2760907          0.4358
NGA-ADM2-72505758B27615672         0.4553
NGA-ADM2-72505758B27700910         0.0455
NGA-ADM2-72505758B27714394         0.7449
NGA-ADM2-72505758B27717699         0.7074
NGA-ADM2-72505758B27989153         0.0555
NGA-ADM2-72505758B28102942         0.0362
NGA-ADM2-72505758B28219123         0.0000
NGA-ADM2-72505758B28322663         0.1308
NGA-ADM2-72505758B28358277         0.1308
NGA-ADM2-72505758B28448754         0.3612
NGA-ADM2-72505758B28451778         0.3040
NGA-ADM2-72505758B28517619         0.2171
NGA-ADM2-72505758B28558302         0.6452
NGA-ADM2-72505758B28564088         0.0977
NGA-ADM2-72505758B28688505         0.1768
NGA-ADM2-72505758B28779634         0.6724
NGA-ADM2-72505758B28994882         0.2424
NGA-ADM2-72505758B29272053         0.0113
NGA-ADM2-72505758B29476596         0.3260
NGA-ADM2-72505758B29578266         0.0127
NGA-ADM2-72505758B29634978         0.1768
NGA-ADM2-72505758B29748439         0.6309
NGA-ADM2-72505758B29886865         0.5878
NGA-ADM2-72505758B30062209         0.1768
NGA-ADM2-72505758B30286847         0.1768
NGA-ADM2-72505758B30316327         0.0084
NGA-ADM2-72505758B30341250         0.2412
NGA-ADM2-72505758B30347581         0.0555
NGA-ADM2-72505758B30546335         0.0005
NGA-ADM2-72505758B30682486         0.0421
NGA-ADM2-72505758B3073896          0.0407
NGA-ADM2-72505758B3096768          0.0421
NGA-ADM2-72505758B31033090         0.9177
NGA-ADM2-72505758B31054894         0.3799
NGA-ADM2-72505758B31195973         0.0421
NGA-ADM2-72505758B31206848         0.3516
NGA-ADM2-72505758B31230586         0.0000
NGA-ADM2-72505758B31246828         0.4517
NGA-ADM2-72505758B31287755         0.1768
NGA-ADM2-72505758B31299772         0.4790
NGA-ADM2-72505758B31351375         0.7558
NGA-ADM2-72505758B31542029         0.5454
NGA-ADM2-72505758B31597260         0.0000
NGA-ADM2-72505758B31818357         0.0977
NGA-ADM2-72505758B31818553         0.0977
NGA-ADM2-72505758B3188194          0.3831
NGA-ADM2-72505758B31996608         0.6479
NGA-ADM2-72505758B32139672         0.0676
NGA-ADM2-72505758B32177909         0.4667
NGA-ADM2-72505758B32188730         0.2963
NGA-ADM2-72505758B32218397         0.1768
NGA-ADM2-72505758B32330173         0.1811
NGA-ADM2-72505758B32419485         0.0555
NGA-ADM2-72505758B32554889         0.2901
NGA-ADM2-72505758B32611817         0.1758
NGA-ADM2-72505758B32630687         0.7032
NGA-ADM2-72505758B32774266         0.0734
NGA-ADM2-72505758B32794130         0.5283
NGA-ADM2-72505758B32949816         0.0734
NGA-ADM2-72505758B3304967          0.0734
NGA-ADM2-72505758B33054765         0.0000
NGA-ADM2-72505758B33108582         0.0555
NGA-ADM2-72505758B3317503          0.0000
NGA-ADM2-72505758B33219881         0.0734
NGA-ADM2-72505758B33244779         0.8919
NGA-ADM2-72505758B33343517         0.4590
NGA-ADM2-72505758B33542533         0.6261
NGA-ADM2-72505758B33577737         0.9489
NGA-ADM2-72505758B3369984          0.4479
NGA-ADM2-72505758B34009830         0.1768
NGA-ADM2-72505758B34036858         0.0042
NGA-ADM2-72505758B34194291         0.1768
NGA-ADM2-72505758B34380318         0.0009
NGA-ADM2-72505758B34441411         0.2424
NGA-ADM2-72505758B34494634         0.2472
NGA-ADM2-72505758B34508441         0.1768
NGA-ADM2-72505758B34643703         0.1338
NGA-ADM2-72505758B34822167         0.0974
NGA-ADM2-72505758B34881213         0.1768
NGA-ADM2-72505758B35176966         0.2948
NGA-ADM2-72505758B35597270         0.0478
NGA-ADM2-72505758B35626837         0.0977
NGA-ADM2-72505758B35748968         0.2424
NGA-ADM2-72505758B35936626         0.0421
NGA-ADM2-72505758B36147146         0.6556
NGA-ADM2-72505758B3618695          0.3166
NGA-ADM2-72505758B36277624         0.6760
NGA-ADM2-72505758B36341125         0.0734
NGA-ADM2-72505758B36411974         0.1308
NGA-ADM2-72505758B36631288         0.1308
NGA-ADM2-72505758B36739173         0.0000
NGA-ADM2-72505758B36818221         0.6641
NGA-ADM2-72505758B36829366         0.0703
NGA-ADM2-72505758B36860554         0.6028
NGA-ADM2-72505758B36958634         0.0595
NGA-ADM2-72505758B37006139         0.0000
NGA-ADM2-72505758B37235287         0.0421
NGA-ADM2-72505758B3729824          0.3693
NGA-ADM2-72505758B37546318         0.0066
NGA-ADM2-72505758B37687991         0.1308
NGA-ADM2-72505758B3771557          0.6446
NGA-ADM2-72505758B37718139         0.3646
NGA-ADM2-72505758B38224950         0.8212
NGA-ADM2-72505758B3838497          0.0000
NGA-ADM2-72505758B38387184         0.0977
NGA-ADM2-72505758B38470188         0.1308
NGA-ADM2-72505758B38532832         0.0567
NGA-ADM2-72505758B38565081         0.2622
NGA-ADM2-72505758B38716464         0.6181
NGA-ADM2-72505758B38827784         0.6296
NGA-ADM2-72505758B38868411         0.0977
NGA-ADM2-72505758B38957187         0.0998
NGA-ADM2-72505758B38976800         0.0000
NGA-ADM2-72505758B38989055         0.0868
NGA-ADM2-72505758B39059766         0.3604
NGA-ADM2-72505758B39110166         0.0051
NGA-ADM2-72505758B39194027         0.2487
NGA-ADM2-72505758B39432389         0.8246
NGA-ADM2-72505758B39446185         0.1768
NGA-ADM2-72505758B39689947         0.1308
NGA-ADM2-72505758B40149693         0.0037
NGA-ADM2-72505758B40157454         0.0000
NGA-ADM2-72505758B40428434         0.1308
NGA-ADM2-72505758B40532579         0.9770
NGA-ADM2-72505758B40651914         0.9821
NGA-ADM2-72505758B40667848         0.0430
NGA-ADM2-72505758B40714647         0.6710
NGA-ADM2-72505758B40744784         0.3812
NGA-ADM2-72505758B40746170         0.1383
NGA-ADM2-72505758B40877575         0.4700
NGA-ADM2-72505758B40987774         0.5361
NGA-ADM2-72505758B41151402         0.1768
NGA-ADM2-72505758B41263993         0.4612
NGA-ADM2-72505758B41363947         0.0555
NGA-ADM2-72505758B41458967         0.2410
NGA-ADM2-72505758B41522993         0.0014
NGA-ADM2-72505758B41606003         0.3099
NGA-ADM2-72505758B41747981         0.0977
NGA-ADM2-72505758B41820351         0.0977
NGA-ADM2-72505758B41923004         0.5000
NGA-ADM2-72505758B41928930         0.3764
NGA-ADM2-72505758B41934932         0.1705
NGA-ADM2-72505758B41955915         0.9626
NGA-ADM2-72505758B4198149          0.4336
NGA-ADM2-72505758B42001588         0.3402
NGA-ADM2-72505758B42014722         0.0555
NGA-ADM2-72505758B42099323         0.1768
NGA-ADM2-72505758B42200288         0.0734
NGA-ADM2-72505758B42248280         0.0000
NGA-ADM2-72505758B42260172         0.0139
NGA-ADM2-72505758B42412373         0.0734
NGA-ADM2-72505758B42533808         0.4550
NGA-ADM2-72505758B42614095         0.1308
NGA-ADM2-72505758B4268401          0.0091
NGA-ADM2-72505758B42691841         0.4594
NGA-ADM2-72505758B42781808         0.6796
NGA-ADM2-72505758B42822246         0.8817
NGA-ADM2-72505758B43208251         0.2883
NGA-ADM2-72505758B43213978         0.7026
NGA-ADM2-72505758B43516104         0.4052
NGA-ADM2-72505758B43671176         0.1777
NGA-ADM2-72505758B4371453          0.0271
NGA-ADM2-72505758B43939903         0.0734
NGA-ADM2-72505758B43980846         0.0977
NGA-ADM2-72505758B44064464         0.1001
NGA-ADM2-72505758B44073392         0.8251
NGA-ADM2-72505758B4407900          0.9779
NGA-ADM2-72505758B44145348         0.5071
NGA-ADM2-72505758B44194354         0.1768
NGA-ADM2-72505758B44226036         0.1623
NGA-ADM2-72505758B44240493         0.6860
NGA-ADM2-72505758B44273667         0.4772
NGA-ADM2-72505758B44395382         0.8343
NGA-ADM2-72505758B44548256         0.0282
NGA-ADM2-72505758B44695959         0.0734
NGA-ADM2-72505758B44831066         0.0000
NGA-ADM2-72505758B44941782         0.0185
NGA-ADM2-72505758B45015575         0.0895
NGA-ADM2-72505758B45047614         0.0001
NGA-ADM2-72505758B4505528          0.6887
NGA-ADM2-72505758B45148365         0.1308
NGA-ADM2-72505758B45209095         0.6647
NGA-ADM2-72505758B45319201         0.1308
NGA-ADM2-72505758B4532539          0.0977
NGA-ADM2-72505758B45363429         0.3735
NGA-ADM2-72505758B45556353         0.5374
NGA-ADM2-72505758B45800050         0.4152
NGA-ADM2-72505758B4580856          0.0020
NGA-ADM2-72505758B45966975         0.1768
NGA-ADM2-72505758B46314370         0.0000
NGA-ADM2-72505758B46349170         0.5831
NGA-ADM2-72505758B4635888          0.5403
NGA-ADM2-72505758B46467475         0.3500
NGA-ADM2-72505758B46624629         0.9499
NGA-ADM2-72505758B46727460         0.1766
NGA-ADM2-72505758B46745149         0.0433
NGA-ADM2-72505758B46906771         0.7816
NGA-ADM2-72505758B46945820         0.0025
NGA-ADM2-72505758B47092163         0.4012
NGA-ADM2-72505758B47276571         0.0118
NGA-ADM2-72505758B47502716         0.5489
NGA-ADM2-72505758B47558893         0.1338
NGA-ADM2-72505758B47569121         0.0000
NGA-ADM2-72505758B47597427         0.0977
NGA-ADM2-72505758B47868503         0.1308
NGA-ADM2-72505758B47972472         0.2349
NGA-ADM2-72505758B48054636         0.9115
NGA-ADM2-72505758B48100225         0.6118
NGA-ADM2-72505758B48120393         0.4446
NGA-ADM2-72505758B48161598         0.0421
NGA-ADM2-72505758B48168473         0.3890
NGA-ADM2-72505758B48317000         0.2424
NGA-ADM2-72505758B485966           0.4267
NGA-ADM2-72505758B48644703         0.1308
NGA-ADM2-72505758B48817484         0.1768
NGA-ADM2-72505758B48854878         0.5862
NGA-ADM2-72505758B48978893         0.0734
NGA-ADM2-72505758B48991596         0.6442
NGA-ADM2-72505758B49088403         0.0977
NGA-ADM2-72505758B49090421         0.6472
NGA-ADM2-72505758B49591931         0.2206
NGA-ADM2-72505758B49639858         0.1537
NGA-ADM2-72505758B49756103         0.7216
NGA-ADM2-72505758B49835051         0.0734
NGA-ADM2-72505758B49932072         0.0075
NGA-ADM2-72505758B50036017         0.6030
NGA-ADM2-72505758B50480947         0.5461
NGA-ADM2-72505758B50499057         0.1768
NGA-ADM2-72505758B50500527         0.1308
NGA-ADM2-72505758B50566658         0.1074
NGA-ADM2-72505758B50825869         0.1768
NGA-ADM2-72505758B5084877          0.5099
NGA-ADM2-72505758B50871717         0.0074
NGA-ADM2-72505758B5090387          0.0734
NGA-ADM2-72505758B50946056         0.0006
NGA-ADM2-72505758B51199259         0.5905
NGA-ADM2-72505758B5121987          0.5791
NGA-ADM2-72505758B51332829         0.8717
NGA-ADM2-72505758B51610317         0.7010
NGA-ADM2-72505758B5164375          0.1308
NGA-ADM2-72505758B51901764         0.6140
NGA-ADM2-72505758B51902603         0.5376
NGA-ADM2-72505758B52057503         0.0622
NGA-ADM2-72505758B52690633         0.4012
NGA-ADM2-72505758B52856855         0.8832
NGA-ADM2-72505758B528653           0.1768
NGA-ADM2-72505758B52884892         0.3402
NGA-ADM2-72505758B53166523         0.2191
NGA-ADM2-72505758B53799809         0.4350
NGA-ADM2-72505758B53984624         0.6446
NGA-ADM2-72505758B54152816         0.0977
NGA-ADM2-72505758B54320674         0.1768
NGA-ADM2-72505758B54394765         0.0860
NGA-ADM2-72505758B54495757         0.9475
NGA-ADM2-72505758B54638889         0.0751
NGA-ADM2-72505758B54686951         0.0555
NGA-ADM2-72505758B54729887         0.7504
NGA-ADM2-72505758B54838860         0.0977
NGA-ADM2-72505758B54904664         0.4838
NGA-ADM2-72505758B55254312         0.0567
NGA-ADM2-72505758B55275980         0.4333
NGA-ADM2-72505758B55501663         0.1908
NGA-ADM2-72505758B5575139          0.3214
NGA-ADM2-72505758B5578796          0.2424
NGA-ADM2-72505758B5592240          0.0977
NGA-ADM2-72505758B56024064         0.1308
NGA-ADM2-72505758B56032953         0.1338
NGA-ADM2-72505758B56149510         0.1994
NGA-ADM2-72505758B5623512          0.7935
NGA-ADM2-72505758B56331112         0.0734
NGA-ADM2-72505758B5637778          0.1308
NGA-ADM2-72505758B56394634         0.1308
NGA-ADM2-72505758B56444221         0.1044
NGA-ADM2-72505758B56744751         0.0047
NGA-ADM2-72505758B56799054         0.6402
NGA-ADM2-72505758B56816258         0.0555
NGA-ADM2-72505758B56925175         0.7488
NGA-ADM2-72505758B56934856         0.6428
NGA-ADM2-72505758B56955836         0.3302
NGA-ADM2-72505758B57073987         0.2424
NGA-ADM2-72505758B5716143          0.2425
NGA-ADM2-72505758B57235084         0.4986
NGA-ADM2-72505758B57280378         0.1742
NGA-ADM2-72505758B57306951         0.8372
NGA-ADM2-72505758B57412385         0.0237
NGA-ADM2-72505758B57514033         0.4133
NGA-ADM2-72505758B57638513         0.1010
NGA-ADM2-72505758B57815144         0.0977
NGA-ADM2-72505758B57963290         0.0734
NGA-ADM2-72505758B58223447         0.0000
NGA-ADM2-72505758B5824220          0.0734
NGA-ADM2-72505758B58295941         0.1768
NGA-ADM2-72505758B5834354          0.8258
NGA-ADM2-72505758B58432429         0.1471
NGA-ADM2-72505758B58640661         0.8899
NGA-ADM2-72505758B5875612          0.0999
NGA-ADM2-72505758B59054861         0.3946
NGA-ADM2-72505758B59091347         0.0001
NGA-ADM2-72505758B59710243         0.1308
NGA-ADM2-72505758B5987673          0.0977
NGA-ADM2-72505758B59879704         0.0137
NGA-ADM2-72505758B60171436         0.0025
NGA-ADM2-72505758B60425686         0.1308
NGA-ADM2-72505758B60502549         0.0977
NGA-ADM2-72505758B60765301         0.2977
NGA-ADM2-72505758B61058152         0.4185
NGA-ADM2-72505758B61328021         0.8110
NGA-ADM2-72505758B6140913          0.0000
NGA-ADM2-72505758B614754           0.1308
NGA-ADM2-72505758B61554030         0.0999
NGA-ADM2-72505758B61584452         0.0977
NGA-ADM2-72505758B61679125         0.0977
NGA-ADM2-72505758B6178712          0.1308
NGA-ADM2-72505758B61803394         0.0977
NGA-ADM2-72505758B61833663         0.3498
NGA-ADM2-72505758B61849091         0.4593
NGA-ADM2-72505758B6187391          0.8611
NGA-ADM2-72505758B61968000         0.1163
NGA-ADM2-72505758B62110738         0.0000
NGA-ADM2-72505758B62204667         0.2498
NGA-ADM2-72505758B62431971         0.6039
NGA-ADM2-72505758B62522831         0.0001
NGA-ADM2-72505758B6253464          0.0977
NGA-ADM2-72505758B62747799         0.0000
NGA-ADM2-72505758B62799042         0.0430
NGA-ADM2-72505758B62812657         0.0001
NGA-ADM2-72505758B62943467         0.7939
NGA-ADM2-72505758B62956588         0.0008
NGA-ADM2-72505758B63001706         0.0617
NGA-ADM2-72505758B63074678         0.9114
NGA-ADM2-72505758B63382694         0.6197
NGA-ADM2-72505758B63641874         0.0020
NGA-ADM2-72505758B63662909         0.8175
NGA-ADM2-72505758B636923           0.5418
NGA-ADM2-72505758B63774666         0.2424
NGA-ADM2-72505758B63992612         0.0734
NGA-ADM2-72505758B64173383         0.3485
NGA-ADM2-72505758B64244244         0.0977
NGA-ADM2-72505758B64250128         0.0977
NGA-ADM2-72505758B64450018         0.0000
NGA-ADM2-72505758B64474046         0.7780
NGA-ADM2-72505758B64572421         0.1768
NGA-ADM2-72505758B64703850         0.3406
NGA-ADM2-72505758B64792691         0.0000
NGA-ADM2-72505758B6536467          0.6424
NGA-ADM2-72505758B65494204         0.2424
NGA-ADM2-72505758B65514383         0.7056
NGA-ADM2-72505758B65565348         0.0071
NGA-ADM2-72505758B65644548         0.0883
NGA-ADM2-72505758B65886725         0.3793
NGA-ADM2-72505758B65916530         0.0977
NGA-ADM2-72505758B66076488         0.1308
NGA-ADM2-72505758B66114245         0.3666
NGA-ADM2-72505758B6619157          0.0734
NGA-ADM2-72505758B66230476         0.2843
NGA-ADM2-72505758B66286397         0.0567
NGA-ADM2-72505758B66300646         0.0734
NGA-ADM2-72505758B66308875         0.5808
NGA-ADM2-72505758B66311687         0.5982
NGA-ADM2-72505758B66384798         0.2512
NGA-ADM2-72505758B6675111          0.6418
NGA-ADM2-72505758B67103889         0.7827
NGA-ADM2-72505758B67188591         0.2493
NGA-ADM2-72505758B67228552         0.8703
NGA-ADM2-72505758B67267634         0.0005
NGA-ADM2-72505758B67283121         0.0000
NGA-ADM2-72505758B6732783          0.5736
NGA-ADM2-72505758B67592189         0.1768
NGA-ADM2-72505758B67778003         0.7899
NGA-ADM2-72505758B6786568          0.0977
NGA-ADM2-72505758B67905963         0.4521
NGA-ADM2-72505758B68001848         0.4234
NGA-ADM2-72505758B68194313         0.1308
NGA-ADM2-72505758B68200680         0.8456
NGA-ADM2-72505758B68356378         0.0320
NGA-ADM2-72505758B68486014         0.0000
NGA-ADM2-72505758B68552788         0.3124
NGA-ADM2-72505758B68678547         0.8326
NGA-ADM2-72505758B6884405          0.1308
NGA-ADM2-72505758B68875813         0.4317
NGA-ADM2-72505758B68878432         0.0734
NGA-ADM2-72505758B68896460         0.7672
NGA-ADM2-72505758B69061814         0.3121
NGA-ADM2-72505758B69218817         0.4786
NGA-ADM2-72505758B69255840         0.4462
NGA-ADM2-72505758B69267419         0.0555
NGA-ADM2-72505758B69319692         0.0734
NGA-ADM2-72505758B69353048         0.0977
NGA-ADM2-72505758B69357183         0.0088
NGA-ADM2-72505758B69384871         0.0085
NGA-ADM2-72505758B69642516         0.1258
NGA-ADM2-72505758B69788799         0.0734
NGA-ADM2-72505758B70059085         0.1654
NGA-ADM2-72505758B70119517         0.1690
NGA-ADM2-72505758B70167647         0.6812
NGA-ADM2-72505758B70182243         0.3377
NGA-ADM2-72505758B70270736         0.2424
NGA-ADM2-72505758B70271338         0.0006
NGA-ADM2-72505758B70495723         0.9083
NGA-ADM2-72505758B70869724         0.0734
NGA-ADM2-72505758B70905299         0.0734
NGA-ADM2-72505758B70998471         0.2424
NGA-ADM2-72505758B71477681         0.7416
NGA-ADM2-72505758B718280           0.0000
NGA-ADM2-72505758B7184000          0.2424
NGA-ADM2-72505758B71906601         0.2424
NGA-ADM2-72505758B71918331         0.3350
NGA-ADM2-72505758B71990951         0.0977
NGA-ADM2-72505758B72019004         0.9224
NGA-ADM2-72505758B72123387         0.0772
NGA-ADM2-72505758B7217003          0.2424
NGA-ADM2-72505758B72331537         0.1308
NGA-ADM2-72505758B72340078         0.2525
NGA-ADM2-72505758B72369186         0.0000
NGA-ADM2-72505758B72408011         0.1811
NGA-ADM2-72505758B72527598         0.2353
NGA-ADM2-72505758B72583543         0.7689
NGA-ADM2-72505758B72901624         0.3359
NGA-ADM2-72505758B72996990         0.1308
NGA-ADM2-72505758B73155659         0.4399
NGA-ADM2-72505758B73169585         0.6739
NGA-ADM2-72505758B7318634          0.0006
NGA-ADM2-72505758B7324564          0.0206
NGA-ADM2-72505758B73267274         0.2217
NGA-ADM2-72505758B73302858         0.1308
NGA-ADM2-72505758B73332929         0.0414
NGA-ADM2-72505758B73850861         0.0021
NGA-ADM2-72505758B74167895         0.0977
NGA-ADM2-72505758B74224076         0.5697
NGA-ADM2-72505758B74273353         0.2610
NGA-ADM2-72505758B74442045         0.0000
NGA-ADM2-72505758B74527534         0.5385
NGA-ADM2-72505758B74576641         0.2186
NGA-ADM2-72505758B74718112         0.0977
NGA-ADM2-72505758B7490938          0.5492
NGA-ADM2-72505758B75034141         0.0000
NGA-ADM2-72505758B75040986         0.4340
NGA-ADM2-72505758B75230852         0.1307
NGA-ADM2-72505758B7553151          0.0003
NGA-ADM2-72505758B75536077         0.0198
NGA-ADM2-72505758B75784992         0.1308
NGA-ADM2-72505758B75801679         0.1308
NGA-ADM2-72505758B75908239         0.0734
NGA-ADM2-72505758B75983929         0.8157
NGA-ADM2-72505758B76052259         0.5306
NGA-ADM2-72505758B76392163         0.1235
NGA-ADM2-72505758B76566778         0.5871
NGA-ADM2-72505758B7691229          0.9114
NGA-ADM2-72505758B77062793         0.2487
NGA-ADM2-72505758B7732292          0.2356
NGA-ADM2-72505758B77767589         0.6413
NGA-ADM2-72505758B77907079         0.1754
NGA-ADM2-72505758B78258316         0.9474
NGA-ADM2-72505758B783054           0.0092
NGA-ADM2-72505758B78395267         0.5540
NGA-ADM2-72505758B7845389          0.1900
NGA-ADM2-72505758B78492046         0.1920
NGA-ADM2-72505758B78527113         0.0751
NGA-ADM2-72505758B78527729         0.0751
NGA-ADM2-72505758B78555816         0.5703
NGA-ADM2-72505758B7855953          0.0483
NGA-ADM2-72505758B78597532         0.1784
NGA-ADM2-72505758B78619683         0.5431
NGA-ADM2-72505758B78698197         0.9435
NGA-ADM2-72505758B78741094         0.1308
NGA-ADM2-72505758B79155077         0.0977
NGA-ADM2-72505758B79178637         0.0422
NGA-ADM2-72505758B79193959         0.0734
NGA-ADM2-72505758B79316383         0.3924
NGA-ADM2-72505758B79444654         0.0000
NGA-ADM2-72505758B79493017         0.2206
NGA-ADM2-72505758B7968540          0.1471
NGA-ADM2-72505758B79803896         0.2424
NGA-ADM2-72505758B79815894         0.7658
NGA-ADM2-72505758B79902123         0.1768
NGA-ADM2-72505758B79945925         0.9860
NGA-ADM2-72505758B79983056         0.6698
NGA-ADM2-72505758B80057854         0.0317
NGA-ADM2-72505758B80290097         0.3104
NGA-ADM2-72505758B8045942          0.0977
NGA-ADM2-72505758B80517430         0.0555
NGA-ADM2-72505758B80733792         0.4193
NGA-ADM2-72505758B80737371         0.6777
NGA-ADM2-72505758B80966644         0.0977
NGA-ADM2-72505758B81144344         0.4335
NGA-ADM2-72505758B8143254          0.1270
NGA-ADM2-72505758B8152058          0.5291
NGA-ADM2-72505758B81562716         0.0015
NGA-ADM2-72505758B81594808         0.4889
NGA-ADM2-72505758B81600634         0.0734
NGA-ADM2-72505758B81840583         0.5902
NGA-ADM2-72505758B8232613          0.9139
NGA-ADM2-72505758B82571199         0.0734
NGA-ADM2-72505758B82611067         0.8759
NGA-ADM2-72505758B82612540         0.6112
NGA-ADM2-72505758B82650021         0.1768
NGA-ADM2-72505758B82952463         0.5613
NGA-ADM2-72505758B82980400         0.0458
NGA-ADM2-72505758B83115922         0.0004
NGA-ADM2-72505758B83213265         0.7029
NGA-ADM2-72505758B83356374         0.0977
NGA-ADM2-72505758B83595220         0.2424
NGA-ADM2-72505758B83712041         0.0977
NGA-ADM2-72505758B83816053         0.4136
NGA-ADM2-72505758B83963728         0.0949
NGA-ADM2-72505758B83971794         0.0000
NGA-ADM2-72505758B84114048         0.8453
NGA-ADM2-72505758B84194123         0.1768
NGA-ADM2-72505758B84339715         0.3053
NGA-ADM2-72505758B84457876         0.4150
NGA-ADM2-72505758B84478450         0.2482
NGA-ADM2-72505758B84831958         0.4138
NGA-ADM2-72505758B84865629         0.0004
NGA-ADM2-72505758B85138406         0.1768
NGA-ADM2-72505758B85275479         0.8059
NGA-ADM2-72505758B85519087         0.1308
NGA-ADM2-72505758B86064137         0.0734
NGA-ADM2-72505758B86185926         0.0701
NGA-ADM2-72505758B8622199          0.0106
NGA-ADM2-72505758B86358915         0.4523
NGA-ADM2-72505758B8652160          0.0345
NGA-ADM2-72505758B86583227         0.0060
NGA-ADM2-72505758B86734523         0.0421
NGA-ADM2-72505758B86763634         0.1308
NGA-ADM2-72505758B86773608         0.9139
NGA-ADM2-72505758B86821483         0.1444
NGA-ADM2-72505758B8687564          0.0977
NGA-ADM2-72505758B86879364         0.0555
NGA-ADM2-72505758B8726241          0.0523
NGA-ADM2-72505758B8775504          0.0000
NGA-ADM2-72505758B87811615         0.0001
NGA-ADM2-72505758B87995813         0.1768
NGA-ADM2-72505758B88150775         0.0007
NGA-ADM2-72505758B88452088         0.5211
NGA-ADM2-72505758B88587475         0.1308
NGA-ADM2-72505758B88727897         0.0579
NGA-ADM2-72505758B88761962         0.9704
NGA-ADM2-72505758B88921590         0.0977
NGA-ADM2-72505758B88925335         0.1768
NGA-ADM2-72505758B8918259          0.0263
NGA-ADM2-72505758B89235976         0.7863
NGA-ADM2-72505758B89515171         0.0000
NGA-ADM2-72505758B8960534          0.0200
NGA-ADM2-72505758B89722002         0.2957
NGA-ADM2-72505758B89731144         0.0011
NGA-ADM2-72505758B89894474         0.6032
NGA-ADM2-72505758B90027140         0.0977
NGA-ADM2-72505758B90250628         0.0134
NGA-ADM2-72505758B90811761         0.0485
NGA-ADM2-72505758B91050715         0.8449
NGA-ADM2-72505758B91135250         0.0000
NGA-ADM2-72505758B913149           0.2759
NGA-ADM2-72505758B91510140         0.0000
NGA-ADM2-72505758B91579398         0.0057
NGA-ADM2-72505758B91650930         0.0000
NGA-ADM2-72505758B91687942         0.0977
NGA-ADM2-72505758B92105435         0.3930
NGA-ADM2-72505758B92139849         0.2817
NGA-ADM2-72505758B92277191         0.3806
NGA-ADM2-72505758B92576019         0.1020
NGA-ADM2-72505758B92786354         0.7691
NGA-ADM2-72505758B92819273         0.0977
NGA-ADM2-72505758B92921679         0.7442
NGA-ADM2-72505758B92954057         0.7957
NGA-ADM2-72505758B93424331         0.0977
NGA-ADM2-72505758B93427284         0.1351
NGA-ADM2-72505758B93593012         0.0002
NGA-ADM2-72505758B93638472         0.3217
NGA-ADM2-72505758B93649439         0.1338
NGA-ADM2-72505758B93709657         0.0977
NGA-ADM2-72505758B93737389         0.5076
NGA-ADM2-72505758B93761587         0.0734
NGA-ADM2-72505758B93767969         0.0555
NGA-ADM2-72505758B94189690         0.6446
NGA-ADM2-72505758B94509825         0.1308
NGA-ADM2-72505758B94606913         0.0001
NGA-ADM2-72505758B94629448         0.1308
NGA-ADM2-72505758B94685339         0.1768
NGA-ADM2-72505758B94886311         0.0000
NGA-ADM2-72505758B94925970         0.0000
NGA-ADM2-72505758B94954595         0.0555
NGA-ADM2-72505758B95154533         0.0016
NGA-ADM2-72505758B95191090         0.1768
NGA-ADM2-72505758B95323810         0.1308
NGA-ADM2-72505758B95411855         0.2955
NGA-ADM2-72505758B95429572         0.7436
NGA-ADM2-72505758B95534398         0.4686
NGA-ADM2-72505758B95566521         0.9052
NGA-ADM2-72505758B95606818         0.1705
NGA-ADM2-72505758B95781523         0.0734
NGA-ADM2-72505758B9585780          0.0928
NGA-ADM2-72505758B95859729         0.7308
NGA-ADM2-72505758B95872281         0.4116
NGA-ADM2-72505758B95999274         0.1308
NGA-ADM2-72505758B9609327          0.1308
NGA-ADM2-72505758B9615674          0.3510
NGA-ADM2-72505758B96206882         0.0031
NGA-ADM2-72505758B96230569         0.8365
NGA-ADM2-72505758B9625976          0.0024
NGA-ADM2-72505758B96315687         0.7866
NGA-ADM2-72505758B96375167         0.9211
NGA-ADM2-72505758B96655345         0.1308
NGA-ADM2-72505758B9668183          0.6812
NGA-ADM2-72505758B96685701         0.0734
NGA-ADM2-72505758B96746323         0.9801
NGA-ADM2-72505758B9692286          0.1768
NGA-ADM2-72505758B96981662         0.1768
NGA-ADM2-72505758B97139317         0.1768
NGA-ADM2-72505758B97184317         0.7869
NGA-ADM2-72505758B9725515          0.2424
NGA-ADM2-72505758B97294598         0.0139
NGA-ADM2-72505758B97405906         0.9649
NGA-ADM2-72505758B97448934         0.1768
NGA-ADM2-72505758B9755199          0.5873
NGA-ADM2-72505758B98057596         0.0413
NGA-ADM2-72505758B98072407         0.1040
NGA-ADM2-72505758B98086722         0.3014
NGA-ADM2-72505758B98116860         0.6409
NGA-ADM2-72505758B98120163         0.1768
NGA-ADM2-72505758B98218468         0.0977
NGA-ADM2-72505758B98262124         0.0687
NGA-ADM2-72505758B98593855         0.0021
NGA-ADM2-72505758B98658548         0.7556
NGA-ADM2-72505758B98737176         0.1768
NGA-ADM2-72505758B98765613         0.0914
NGA-ADM2-72505758B99221548         0.5477
NGA-ADM2-72505758B99270352         0.3985
NGA-ADM2-72505758B99641746         0.1338
NGA-ADM2-72505758B99650649         0.0000
NGA-ADM2-72505758B99764805         0.1308
NGA-ADM2-72505758B9986554          0.7457
NGA-ADM2-72505758B99970923         0.7119</code></pre>
</div>
</div>
<ul>
<li>Mapping the local Moran’s I: I append the local Moran’s I dataframe onto Nigeria spatial polygon dataframe</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a>nga_wp.localMI <span class="ot">&lt;-</span> <span class="fu">cbind</span>(nga_wp,localMI) <span class="sc">%&gt;%</span></span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">Pr.Ii =</span> Pr.z....E.Ii..)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li>Mapping local Moran’s I values: Using choropleth mapping functions of tmap package,I plot the local Moran’s I values by using the code chinks below</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(nga_wp.localMI) <span class="sc">+</span></span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_fill</span>(<span class="at">col =</span> <span class="st">"Ii"</span>, </span>
<span id="cb62-3"><a href="#cb62-3" aria-hidden="true" tabindex="-1"></a>          <span class="at">style =</span> <span class="st">"pretty"</span>,</span>
<span id="cb62-4"><a href="#cb62-4" aria-hidden="true" tabindex="-1"></a>          <span class="at">palette =</span> <span class="st">"RdBu"</span>,</span>
<span id="cb62-5"><a href="#cb62-5" aria-hidden="true" tabindex="-1"></a>          <span class="at">title =</span> <span class="st">"local moran statistics"</span>) <span class="sc">+</span></span>
<span id="cb62-6"><a href="#cb62-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Variable(s) "Ii" contains positive and negative values, so midpoint is set to 0. Set midpoint = NA to show the full spectrum of the color palette.</code></pre>
</div>
<div class="cell-output-display">
<p><img src="Take-home-Ex1_files/figure-html/unnamed-chunk-38-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<ul>
<li>Mapping local Moran’s I p-values</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(nga_wp.localMI) <span class="sc">+</span></span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_fill</span>(<span class="at">col =</span> <span class="st">"Pr.Ii"</span>, </span>
<span id="cb64-3"><a href="#cb64-3" aria-hidden="true" tabindex="-1"></a>          <span class="at">breaks=</span><span class="fu">c</span>(<span class="sc">-</span><span class="cn">Inf</span>, <span class="fl">0.001</span>, <span class="fl">0.01</span>, <span class="fl">0.05</span>, <span class="fl">0.1</span>, <span class="cn">Inf</span>),</span>
<span id="cb64-4"><a href="#cb64-4" aria-hidden="true" tabindex="-1"></a>          <span class="at">palette=</span><span class="st">"-Blues"</span>, </span>
<span id="cb64-5"><a href="#cb64-5" aria-hidden="true" tabindex="-1"></a>          <span class="at">title =</span> <span class="st">"local Moran's I p-values"</span>) <span class="sc">+</span></span>
<span id="cb64-6"><a href="#cb64-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Take-home-Ex1_files/figure-html/unnamed-chunk-39-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<ul>
<li>Mapping both local Moran’s I values and p-values</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a>localMI.map <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(nga_wp.localMI) <span class="sc">+</span></span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_fill</span>(<span class="at">col =</span> <span class="st">"Ii"</span>, </span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a>          <span class="at">style =</span> <span class="st">"pretty"</span>, </span>
<span id="cb65-4"><a href="#cb65-4" aria-hidden="true" tabindex="-1"></a>          <span class="at">title =</span> <span class="st">"local moran statistics"</span>) <span class="sc">+</span></span>
<span id="cb65-5"><a href="#cb65-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>)</span>
<span id="cb65-6"><a href="#cb65-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb65-7"><a href="#cb65-7" aria-hidden="true" tabindex="-1"></a>pvalue.map <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(nga_wp.localMI) <span class="sc">+</span></span>
<span id="cb65-8"><a href="#cb65-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_fill</span>(<span class="at">col =</span> <span class="st">"Pr.Ii"</span>, </span>
<span id="cb65-9"><a href="#cb65-9" aria-hidden="true" tabindex="-1"></a>          <span class="at">breaks=</span><span class="fu">c</span>(<span class="sc">-</span><span class="cn">Inf</span>, <span class="fl">0.001</span>, <span class="fl">0.01</span>, <span class="fl">0.05</span>, <span class="fl">0.1</span>, <span class="cn">Inf</span>),</span>
<span id="cb65-10"><a href="#cb65-10" aria-hidden="true" tabindex="-1"></a>          <span class="at">palette=</span><span class="st">"-Blues"</span>, </span>
<span id="cb65-11"><a href="#cb65-11" aria-hidden="true" tabindex="-1"></a>          <span class="at">title =</span> <span class="st">"local Moran's I p-values"</span>) <span class="sc">+</span></span>
<span id="cb65-12"><a href="#cb65-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>)</span>
<span id="cb65-13"><a href="#cb65-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb65-14"><a href="#cb65-14" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_arrange</span>(localMI.map, pvalue.map, <span class="at">asp=</span><span class="dv">1</span>, <span class="at">ncol=</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Variable(s) "Ii" contains positive and negative values, so midpoint is set to 0. Set midpoint = NA to show the full spectrum of the color palette.</code></pre>
</div>
<div class="cell-output-display">
<p><img src="Take-home-Ex1_files/figure-html/unnamed-chunk-40-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="creating-a-lisa-cluster-map" class="level4">
<h4 class="anchored" data-anchor-id="creating-a-lisa-cluster-map">2.3.1.2 Creating a LISA Cluster Map</h4>
<section id="plotting-moran-scatterplot" class="level5">
<h5 class="anchored" data-anchor-id="plotting-moran-scatterplot">(1) Plotting Moran scatterplot</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a>nci <span class="ot">&lt;-</span> <span class="fu">moran.plot</span>(nga_wp<span class="sc">$</span><span class="st">`</span><span class="at">wpt functional</span><span class="st">`</span>, rswm_q,</span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a>                  <span class="at">labels=</span><span class="fu">as.character</span>(nga_wp<span class="sc">$</span>shapeName), </span>
<span id="cb67-3"><a href="#cb67-3" aria-hidden="true" tabindex="-1"></a>                  <span class="at">xlab=</span><span class="st">"GDPPC 2012"</span>, </span>
<span id="cb67-4"><a href="#cb67-4" aria-hidden="true" tabindex="-1"></a>                  <span class="at">ylab=</span><span class="st">"Spatially Lag GDPPC 2012"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Take-home-Ex1_files/figure-html/unnamed-chunk-41-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>the plot is split in 4 quadrants.</p>
</section>
<section id="plotting-moran-scatterplot-with-standardised-variable" class="level5">
<h5 class="anchored" data-anchor-id="plotting-moran-scatterplot-with-standardised-variable">(2) Plotting Moran scatterplot with standardised variable</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a>nga_wp<span class="sc">$</span>Z.wpt_functional <span class="ot">&lt;-</span> <span class="fu">scale</span>(nga_wp<span class="sc">$</span><span class="st">`</span><span class="at">wpt functional</span><span class="st">`</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb68-2"><a href="#cb68-2" aria-hidden="true" tabindex="-1"></a>  as.vector </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a>nci2 <span class="ot">&lt;-</span> <span class="fu">moran.plot</span>(nga_wp<span class="sc">$</span>Z.wpt_functional, rswm_q,</span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a>                   <span class="at">labels=</span><span class="fu">as.character</span>(nga_wp<span class="sc">$</span>shapeName),</span>
<span id="cb69-3"><a href="#cb69-3" aria-hidden="true" tabindex="-1"></a>                   <span class="at">xlab=</span><span class="st">"z-GDPPC 2012"</span>, </span>
<span id="cb69-4"><a href="#cb69-4" aria-hidden="true" tabindex="-1"></a>                   <span class="at">ylab=</span><span class="st">"Spatially Lag z-GDPPC 2012"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Take-home-Ex1_files/figure-html/unnamed-chunk-43-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>(3) Preparing LISA map classes</p>
</section>
</section>
</section>
</section>
</section>
<section id="hotspot-area-analysis" class="level1">
<h1>3 Hotspot area analysis</h1>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
</div> <!-- /content -->



</body></html>